### ISSUE TITLE
Emulation - Setting percentHeight prevents layout from happening on resize

### ISSUE THREAD

**Issue by yishayw** [apache/royale-asjs#1021]
In this app

```
<?xml version="1.0" encoding="utf-8"?>
<s:Application 
	xmlns:fx="http://ns.adobe.com/mxml/2009"
	xmlns:s="library://ns.apache.org/royale/spark"
	creationComplete="init()"
	xmlns:mx="library://ns.apache.org/royale/mx"
	>
	<fx:Script>
		<![CDATA[
			private function init():void
			{
				myGrandChildGroup.height = 100;
			}
		]]>
	</fx:Script>		
	<s:VGroup id="myVGroup"
		style="background-color: red; alpha: 0.5"
		>
		<s:Group id="myChildGroup" style="background-color: blue; alpha: 0.5" height="100%" width="100%">
			<s:Group id="myGrandChildGroup" style="background-color: yellow; alpha: 0.5" width="100%"/>
		</s:Group>
		<s:Button width="100%" height="20"/>
	</s:VGroup>
</s:Application>

```

Button should be offset 100px from top, instead it floats at the top.

**Comment by yishayw** [comment]
It looks like in SparkLayoutBead

		if ((!isNaN(target.percentWidth)) || (!isNaN(target.percentHeight)))
			if (!sawSizeChanged)
				return false;

Kicks in preventing proper layout from happening.

**Comment by yishayw** [comment]
> It looks like in SparkLayoutBead
> 
> ```
> 	if ((!isNaN(target.percentWidth)) || (!isNaN(target.percentHeight)))
> 		if (!sawSizeChanged)
> 			return false;
> ```
> 
> Kicks in preventing proper layout from happening.

That's not the issue. The issue is that in org.apache.royale.core.LayoutBase.childResizeHandler() host.isHeightSizedToContent() returns true, which prevents performLayout() from happening. 

Woraround is to use top=0, bottom=0 instead of height=100% (which seems inconsistent).

**Comment by aharui** [comment]
If heightIsSizedToContent, then the component should resize/layout in response to the change.  If not sized to content because it is percent sized, it would wait for the parent to layout first.

By setting height=100, then it is explicitly sized, not sized to content, but the framework may not be catching that and forcing a layout on the parent, but it should be.  The height change should cause "heightChange" event which should be picked up by myChildGroup.  That needs to trigger a re-measure and layout of the myVGroup.  myChildGroup's measuredHeight should be 100.

**Comment by yishayw** [comment]
> in org.apache.royale.core.LayoutBase.childResizeHandler() host.isHeightSizedToContent() returns true

I meant returns false, my mistake.

We have this code in UIComponent.isHeightSizedToContent

        if (!isNaN(percentHeight))
            return false;

Everything else you described works in the ChildResize branch.

**Comment by yishayw** [comment]
I can confirm it now works in the ChildResize branch.

**Comment by estanglerbm** [comment]
Should this issue be closed?
