### ISSUE TITLE
AMF problem

### ISSUE THREAD

**Issue by safrizal** [apache/royale-asjs#1039]
latest build, amf not working anymore...
running examples amf/SampleAmfWebApp as server and
royale/RemoteObjectAMFTest as client

code = "Server.Processing"
message = "The supplied destination id is not registered with any service."

**Comment by carlosrovira** [comment]
Hi This could be related to 

https://github.com/apache/royale-asjs/pull/1023

I just reverted it, Can you rebuild Royale localy and test? or wait for new nightly build and report?

Hope @SemiConscious (https://github.com/SemiConscious) can see this problem with you to find what's the problem.

Thanks

**Comment by safrizal** [comment]
Thank you, CR,

examples now working again, my amf projects are working too.
weird, who reviewed this PR ?  you should not commit bugs in this project.

**Comment by SemiConscious** [comment]
@safrizal @carlosrovira @greg-dove - First, I'm really sorry if this change created problems for you. Next: the problem is that the existing code contains bugs - royale AMF (in it's currently reverted state) cannot run the same code as it did under flex because (to cut to the chase) the `NetConnection.send()` function has a significantly different interface - `params` is a single parameter instead of a `...` parameter as it used to be. The question then becomes: is it possible to run Flex-style AMF applications using the new interface? The answer as far as I can see is no, even if you refactor the parameter passing. If it was a matter of refactoring I would have refactored.

I posed this question in my pull request: why has the interface changed? If we could answer that question that would be a good start.

Second - @safrizal how on earth are you getting your AMF services to work without using the target URI, which is currently not being passed to the AMF service at all? Are you just using the failover service hook for when there is no URI? If so ok but that shouldn't mean other people cannot use it in the way that was originally intended.

Happy to work on this more with anyone interested.

**Comment by carlosrovira** [comment]
I think we should wait for @greg-dove review of the PR. There was to different things maybe one is ok and other need to be done in other way

**Comment by safrizal** [comment]
no, don't ask me, they're not my amf services, you should ask to who made these examples.
using your PR, the examples not working, so because i follow examples rules, and my projects become problem too.

i suggest, if you have idea about your PR, you should modify the examples, mxroyale/RemoteObjectAMFTest and
royale/RemoteObjectAMFTest+TestBasic (for clients) and amf/SampleAmfWebApp as server (if any).

if examples changed, and run well, automatically i will follow your rules. just like that.

**Comment by SemiConscious** [comment]
@safrizal, @carlosrovira - thanks, that's all understood. I will try and understand the example failure and why everything appeared to pass before I submitted the change request. I will try extremely hard not to submit pull requests in future that break unit tests or examples! When I have more to add I will submit new pull requests with the two issues addressed separately.

**Comment by carlosrovira** [comment]
Thanks @SemiConscious that's will be great :)
