### ISSUE TITLE
AMFPHP RemoteObject

### ISSUE THREAD

**Issue by Bilbosax** [apache/royale-asjs#1064]
I have spent the last two days trying to get RemoteObject to work in Royale.  I have it working in Flex/AIR just fine, so I have some questions about what is the same or different between Flex and Royale.  I am trying to use mx RemoteObject instead of the js version.  First, here are the parameters that I use in my project:

XML config file    - services-config.xml (this points to the destination)
PHP Classname   - BrokerageService
method to call    - getStates
endpoint             - https://www.mywebsite.com/services/

My code looks like this:

```
<j:beads>
    <js:ClassAliasBead />
</j:beads>

<fx:Declarations>
	<mx:RemoteObject id="brokerageRO" destination="zend" source="BrokerageService" showBusyCursor="false">
		<mx:method name="getStates" result="getStatesResultHandler(event)" fault="databaseFaultHandler(event)"/>
	</mx:RemoteObject>
</fx:Declarations>
```

So I have include the bead <js:ClassAliasBead/>, I include the services-config.xml in my compiler options, and everything else is pretty much the way that it has always been.  But it does not work.

So what do I need to do differently?  

1. Do I need to include the services-config.xml in my compiler options in Royale, and if not, how do I set my destination, source, and endpoints correctly given the data that I presented above?

2.  is it still ok to use the mx:method to call my particular PHP method?

**Comment by carlosrovira** [comment]
1.- MX RemoteObject is the good verions. The version in NET works but is not fully feature complete.
2.- source property could probably work, but is not recommended since you're exposing the name of the source class in PHP (or java, or .NET,...) in the client. I know it was deprecated, but still in the class for backward compatibility. 
3.- Use endPoint:

```xml
<mx:RemoteObject id="serviceResp" fault="onFault(event)"
                         endpoint="http://localhost:8080/messagebroker/websocket-amf"
                         destination="exampleService"/>
```
4.- mx:method is not fully implemented, instead you need to use `Responder`. This is less mxml, but I think the right way to go in a serious app:

```actionscript
var r:Responder = new Responder(onSendSomeProductResult, onFault);
                var t:AsyncToken = serviceResp.sendSomeProduct(product);
                t.addResponder(r);
```

5.- Check `examples/amf` and `examples/mxroyale`
6.- Check docs here: https://apache.github.io/royale-docs/features/loading-external-data/remoteobject

I think @cristallium has a AMF PHP backend working so he probably can give you more advice here

HTH

**Comment by cristallium** [comment]
Hi,

Yes, I succefully used Remote object with AMFPHP (see this post : [https://stackoverflow.com/questions/58241175/how-to-use-amfphp-with-apache-royale](https://stackoverflow.com/questions/58241175/how-to-use-amfphp-with-apache-royale)) .

I also tried it with an old Fluorine (.NET). It is working

I'm not sure that  XML config file - services-config.xml is supported in ApacheRoyale. The best is to set it in AS3 code.

If you use `registerClassAlias("YOUR_CLASS", ApacheRoyale_Class);` you must put this line everytime before calling service. (In FlexAir, put it on Class scope worked, but in Royale, it seem to have only a local fonction scope)

Be careful with CORS.

I'm not sure your endpoint is OK. Calling https://www.mywebsite.com/services/gateway.php via web doesn't show amfphp  message: "amfphp and this gateway are installed correctly"

If it can help, here is my class code to access Php or Fluorine services :
[ServiceCaller.txt](https://github.com/apache/royale-asjs/files/5866471/ServiceCaller.txt)

If you have issues, feel free to post screenshoot of network packets (from dev tools in web navigator)

Regards

**Comment by Bilbosax** [comment]
@cristallium @carlosrovira Thanks for all the feedback.  The endpoint I have works, I just gave a fake address for security reasons.  Unfortunately, I have still not had any success today.  I am choosing the simplest function in my API which just returns a list of state names as an associative array. I don't get much back in terms of an error response that makes a lot of sense.  This is what traces out:

```
org/apache/royale/utils/Language.js
Call was made, but failed - (mx.messaging.messages.ErrorMessage)
  {0}={1},body,[object Object]
  {0}={1},clientId,null
  {0}={1},correlationId,27C88E55-FFDF-3221-9447-600F4182A908
  {0}={1},destination,
  {0}={1},headers,[object Object]
  {0}={1},messageId,AD0825EB-4061-CD1F-3D62-600F41823E11
  {0}={1},timeToLive,0
  {0}={1},timestamp,0
 org/apache/royale/utils/Language.js
```

But my biggest question is this.  Because of rules regarding security with Apple on my mobile apps, my original PHP API is on an SSL secured server and all messages are sent by "https".  I account for this in my config file which is listed here:

```
<?xml version="1.0" encoding="UTF-8"?>
<services-config>
    <services>
        <service id="amfphp-flashremoting-service" class="flex.messaging.services.RemotingService" messageTypes="flex.messaging.messages.RemotingMessage">
            <destination id="zend">
                <channels>
                    <channel ref="my-zend"/>
                </channels>
                <properties>
                    <source>*</source>
                </properties>
            </destination>
        </service>
    </services>
    <channels>
        <channel-definition id="my-zend" class="mx.messaging.channels.SecureAMFChannel">
            <endpoint uri="https://wwwmywebsite.com/services/" class="flex.messaging.endpoints.SecureAMFEndpoint"/>
        </channel-definition>
    </channels>
</services-config>
```
 You can see at the bottom of this file that it specifically mentions a SecureAMFChannel and SecureAMFEndpoint.  Since nobody seems to know if a config file will get compiled correctly in Royale, do you know if there is anything that I need to do special with mx RemoteObject to get it to "speak securely"???

Or do you not think that this is the problem?

**Comment by carlosrovira** [comment]
Hi Bilbo,

I can say that in our apps (Java) our endpoints are https too, so that should work. As well is you check the Java sample project in our repo it uses services-config.xml too. About CORS...don't think is related, or at least I never had a problem with that...maybe PHP is different, but since AMF use to abstract in a binary response, the backend technology, once is working, and we know all this solutions works rigth, should not be a problem.

I always recomend to start with the smallest example in a new project and try to just send a string and then return a string from a backend method. then continue to progress, that way you'll find more easily where's the problem in your legacy project and could solve it. Trying from the start to send and receive data with more possible variants could be very hard to debug and find the problem.

HTH

**Comment by cristallium** [comment]
Hi,
I agree with Carlos, generaly CORS issues are on PHP session id because CORS block setting PHP_SESSID. 
So why not try to set this in your service class :
```
	function test_echo($o){
		return  "-".$o."-";
	}
```

then call test_echo("1"). 

Give a try with ServiceCaller.as that I attached in previous post.
If not working, screen capture of network (Request and response headers) would help to diagnose the issue

**Comment by Bilbosax** [comment]
@cristallium @carlosrovira Again, thanks for your all your help with this frustrating issue for me.  So I installed Fiddler and captured the traffic as you requested.  I posted the Headers and Raw data.  I sure hope that it means more to you than to me :)

![Screenshot (62)](https://user-images.githubusercontent.com/23325601/105914298-2c9fce80-5ffc-11eb-8945-0ae8ad09d822.png)
![Screenshot (63)](https://user-images.githubusercontent.com/23325601/105914318-31fd1900-5ffc-11eb-92e6-32724e0dc743.png)

A couple of things that I notice is that all results posted a "200" which I believe is good, but I still get the error in my app.  One thing that I think is a little strange is that if you navigate to my endpoint at https://dealestator.com/services, it sends you a little file that says "\<p>Zend Amf Endpoint\</p>".  If you look at the Response Raw Data, that string is at the bottom of the Response.  I don't know if that should be there, or if that might mean that it is only making it to my endpoint, but not actually making it all the way to my PHP class.

Thoughts?

**Comment by cristallium** [comment]
Hi,

I don't know Zend Amf, but looking at framewrok Zend manual, end point should be something like http://example.com/server.php (It seems server.php is missing). 
However  as it seem to return something, I beleve your apache config must set `server.php` as default file to serve . But calling directly  https://dealestator.com/services/server.php return 404, I don't know if it's right or not. I thing it's right because of "<p>Zend Amf Endpoint</p>"

Looking at source code of `ZendFramework/library/Zend/Amf/Request/Http.php` then

```
/**
     * Constructor
     *
     * Attempts to read from php://input to get raw POST request; if an error
     * occurs in doing so, or if the AMF body is invalid, the request is declared a
     * fault.
     *
     * @return void
     */
    public function __construct()
    {
        // php://input allows you to read raw POST data. It is a less memory
        // intensive alternative to $HTTP_RAW_POST_DATA and does not need any
        // special php.ini directives
        $amfRequest = file_get_contents('php://input');

        // Check to make sure that we have data on the input stream.
        if ($amfRequest != '') {
            $this->_rawRequest = $amfRequest;
            $this->initialize($amfRequest);
        } else {
            echo '<p>Zend Amf Endpoint</p>' ;
        }
    }
```

So it seem right to return <p>Zend Amf Endpoint</p> if there is no or invalid `amfRequest`, perhaps you should check the way you are calling remote function service ?

Could you show how do you call "getStates" in as3 ?
Regards

**Comment by Bilbosax** [comment]
@cristallium So I had to add the include_path of the ZendFramework library to my php.ini file.  I believe the php endpoint is index.php in my case, that is where all the Server code and the VO mapping go.  This all works like butter in my Flex apps, so I feel it should be a solid setup.  The last line of index.php is "echo($server -> handle());" which I believe spits out the 'Zend Amf Endpoint'.

Here is the MXML that I use to set up the RemoteObject:

`<mx:RemoteObject id="brokerageRO" destination="zend" source="BrokerageService" endpoint="https://www.dealestator.com/services/" showBusyCursor="false"/>`

And here is my actionscript code to call the service and the handlers:

```
protected function testROClickHandler(event:MouseEvent):void {
    //Set Up Responder and Token and call service
	var r:Responder = new Responder(getStatesResultHandler, databaseFaultHandler);
	var t:AsyncToken = brokerageRO.getStates();
	t.addResponder(r);
}

protected function getStatesResultHandler(event:Event):void {
	trace("I freakin got it!!!");
}

protected function databaseFaultHandler(event:FaultEvent):void {
	trace(event.message);
}
```

**Comment by cristallium** [comment]
Hi,
I do a little test. Working from my side. It seem your service return an array with state: Indiana

![image](https://user-images.githubusercontent.com/6851433/106044814-87125b00-60e0-11eb-9f35-70c0be00946d.png)

Here is the full code

[TestRoyale5.zip](https://github.com/apache/royale-asjs/files/5882642/TestRoyale5.zip)

**Comment by Bilbosax** [comment]
That is EXACTLY the answer that you should have gotten!  I am trying to get your code to compile but am running into all kinds of problems, so I tried to create a blank project and am copying stuff in one file at a time.  I seem to be missing stuff in my setup or libraries.  For instance, I can't create a j:ResponsiveView, but I can create j:initialView.  Any ideas?  I'm going to try a clean install of Royale

**Comment by cristallium** [comment]
Hi,
Well done ! I'm glad for your success.
I'm not really sure what is doing "--disable-web-security" for now.
I have done a post on this subject, here is the link 
[https://stackoverflow.com/questions/58240043/how-to-disable-cors-on-chrome-when-using-visual-studio-code-and-using-amf-on-apa](https://stackoverflow.com/questions/58240043/how-to-disable-cors-on-chrome-when-using-visual-studio-code-and-using-amf-on-apa)
Hope enjoy next devs with Apache Royale
Regards
