### ISSUE TITLE
3 Questions - Grid and GridCell

### ISSUE THREAD

**Issue by Bilbosax** [apache/royale-asjs#1070]
I've been reading and studying the Grid/Grid Cell Layout and have a couple of questions I need clarified.

1)  If I have a Grid layout where there are two Grid Cells side by side and a user resizes the browser, is there a way to make the left GridCell end up on bottom instead of on top, like a reverse stacking order?

2) How do I make two GridCells have different widths when they are side-by-side, but the same width when they stack? I'd like the left cell to have a width of one unit, and the right to have a width of two units, for a total of three units when they are side-by-side, but be the same width when they are stacked one above the other.

3) Is there an event that fires when the GridCells shift so that I could change the layout of a GridCells contents when the layout goes from two columns to one column?

Thanks!

**Comment by carlosrovira** [comment]
Hi for 1. just added now "itemsReverse". If you set `itemsReverse="true"`, you get the order of all items inverted in Jewel horizontal and vertical groups and containers or Grids. Will check next two questions...

**Comment by carlosrovira** [comment]
One thing about "itemsReverse" is that `gap` is not considered in this first implementation. I need to take a closer look, but don't seem something hard to do...

**Comment by carlosrovira** [comment]
For 2.- I think you are referring to "itemsSameHeight". Check the end of this page for an example

https://royale.apache.org/tourdejewel/#!grid_panel

**Comment by carlosrovira** [comment]
For 3.- Yes. You have two options:

a) `ResponsiveResizeListener` bead that listens for browser resizing and send events when browser cross a responsive breakpoint. Check In TDJ for an example in `MainContent.mxml` here:

https://github.com/apache/royale-asjs/blob/1c53cd884470578d788165360e604b2981fe1cf6/examples/jewel/TourDeJewel/src/main/royale/MainContent.mxml#L55

In TDJ check the device in Footer Bar bottom right and see how it changes as you resize the width of the browser

b) `ResponsiveSize` bead that can be used to change the size of a Jewel control depending on responsiveness. Check In TDJ for an example in `WelcomSection.mxml` where the main Apache Royale logo change size depending on the size of the screen:

https://github.com/apache/royale-asjs/blob/1c53cd884470578d788165360e604b2981fe1cf6/examples/jewel/TourDeJewel/src/main/royale/WelcomeSection.mxml#L73

Both running examples here: https://royale.apache.org/tourdejewel/

**Comment by carlosrovira** [comment]
Ok 1.- should be solved completely including `gap`.

**Comment by Bilbosax** [comment]
Thanks for the help!  I'll get up to speed quickly I hope and slow down with all the questions ;)

Regarding #2, I have seen a lot of examples in the grid where the  you use different **_HEIGHTS_** to the GridCells, but I haven't seen any where you use different **_WIDTHS_**.  I'd like to have two Grid Cells that are side-by-side with diffent widths.  Is this possible?

**Comment by Bilbosax** [comment]
Tested it out, looks like you can set the widths of individual grid cells if you keep it simple

**Comment by carlosrovira** [comment]
Hi BIlbo,

regarding widths, the concept of "Responsive Grid" is about to divide the total width in columns. A column is a "GridCell". That means you can divide in 12 columns and each column will be 1/12. 2 columns will be each column 1/2 of the total width, and so on. In that way you can use a "numerator" and a "denominator" for type of device. We have setup a phone, tablet, dektop,... widths so you can do: 

```xml
<j:Grid gap="{useGap}">
	<j:GridCell desktopNumerator="1" desktopDenominator="1" tabletNumerator="1" tabletDenominator="1" phoneNumerator="1" phoneDenominator="1">
		<html:Div text="1"/>
	</j:GridCell>
        ...
```

Then in each column you add cards, controls, or any other component. Depending of the component you need to design for different screen widths and that means set the widht to 100%, but in other cases, where a component has a concrete width, you probably will need plan the column so the layout adapts as you change the width. Sometimes you'll need to change the layout others change widths, and so on...

With that in mind you have the tools, but the "responsive game" is a world itself and you need to test thing.

Finally many components in Jewel are implemented with "Adaptiveness" in mind. For example:

- DataField should work better that Flex control, since the DataChooser is designed with devices in mind
- NumericStepper, layout in desktop in the legacy flex way, but in devices the buttons change its position to be more usable and "touchable"
- ComboBox: The popup shows in desktop like in flex, opening from the combo control position, but in phone and tablets the popup shows from the bottom of screen filling the space, and the renders are more "touchable".

HTH
