### ISSUE TITLE
DataGrid Dataprovider doesn't accept XML Values

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#1173]
**In Royale :**
Simple Example : https://paste.apache.org/c2wvg
Output : 
![image](https://user-images.githubusercontent.com/42200979/150558876-6f547c8c-80f4-4953-a566-242e1d1af2b2.png)

Debug Screenshots : There's too many _children in data In flex there was no _children in data so the data was well formed

1) mListXML = ![image](https://user-images.githubusercontent.com/42200979/150559044-7ba60a7e-231a-4a6d-9c3c-2094cf2cf81a.png)

2) ![image](https://user-images.githubusercontent.com/42200979/150559225-c17fce33-d221-492d-8351-b32b79249b95.png)

3) dg.dataprovider = ![image](https://user-images.githubusercontent.com/42200979/150559378-3c17b502-4f20-4f9b-b305-03f396dda722.png)

4) ![image](https://user-images.githubusercontent.com/42200979/150559482-ba9d90ea-2267-4157-98f2-ddae96af19f4.png)

**In Flex Application :** 

Data coming from backend : https://paste.apache.org/wrxgj
DataGrid and resultHandler for DataGrid : https://paste.apache.org/az673

Output :  ![image](https://user-images.githubusercontent.com/42200979/150561415-b5f87fd3-630e-41a3-8eb7-912e5dc180c4.png)

Debug Screenshots
1) event.result = ![image](https://user-images.githubusercontent.com/42200979/150560956-8cf67db5-6965-45fd-82af-cb9c1322a370.png)

2) tmpResult = ![image](https://user-images.githubusercontent.com/42200979/150561107-9bb7bd44-9e87-47d0-83e6-abc10741635c.png)

3) mListXML = ![image](https://user-images.githubusercontent.com/42200979/150560449-16ed821b-7081-4c7c-a50c-180a9e220eb2.png)

4) mListXML.Table = ![image](https://user-images.githubusercontent.com/42200979/150560685-357f5402-f192-4fc8-bdf9-4ad9726fcc2b.png)

5) dgList.dataprovider = ![image](https://user-images.githubusercontent.com/42200979/150560618-0055484b-dfac-40d5-bc17-16edefba74f6.png)

**Comment by estanglerbm** [comment]
Which version of Royale?

**Comment by pashminakazi** [comment]
@estanglerbm Latest version 0.9.9

**Comment by pashminakazi** [comment]
@estanglerbm can you please help me,XML data is not working properly as Dataprovider of DataGrid

**Comment by estanglerbm** [comment]
I haven't run your test case yet, but I think you probably need my changes from PR #1150 (originally part of PR #1127, but which I moved into a new PR due to concerns about PAYG by @Harbs).  These changes involve getting the correct labels, for things like datagrid cells, from XML.

I was extensively using XML to fill mx:AdvancedDataGrid, and it was working well, but it did require extensive changes to Royale.  Most of the really difficult changes (like the XMLNotifier stuff) are already in Royale (that's why I asked about the version), but this one change in how labels are retrieved is the last part that's not in there yet.

I will try your test case, but if you're able to try with the changes from PR #1150, you might get it working sooner.

**Comment by pashminakazi** [comment]
@estanglerbm Thank u so much for your help, changes from PR #1150
<https://github.com/apache/royale-asjs/pull/1150> worked for me.

**Comment by estanglerbm** [comment]
Great.
