### ISSUE TITLE
question: drag and drop in Royale

### ISSUE THREAD

**Issue by jgomer2001** [apache/royale-asjs#1199]
Hi there, this is a general question. Any insight appreciated.

I used to be skilled at as3 + mxmlc back in those times of Flash/Flex glory and I'm happy to find there exists a high quality project that brings this knowledge to the scene again

I'm trying to figure out the capabilities that Royale offers regarding drag and drop. I found issue #1114 so it seems there is basic supported. My target is creating a webapp that allows building flowcharts (somewhat like a BPMN editor), so drag and drop is key. 

There are several diagramimng libraries that would help, they are all Javascript-based but I don't want to mess with JS.

Do you consider I can get any far in a project like this using Apache Royale? does it sound like a tremendeous challenge or something rather manageable for a single dev?

Thanks in advance

**Comment by mjesteve** [comment]
Hi, my experience with D&D is small but it was satisfactory (let's wait for other users to comment their experiences).

As for the diagramming libraries, if they are in js, they can be consumed by Royale without problems (at this point "I'm not an expert" but I currently consume several js libraries in my projects: Apache ECharts, jsCalendar, Inspire-Tree, Virtual-Select, ...)

Consulta la documentación de @externs [[1](https://royale.apache.org/using-external-javascript-libraries-in-apache-royale/)]

**Comment by jgomer2001** [comment]
I would like other contributors to comment as well, thank you all
@joshtynjala @greg-dove @piotrzarzycki21 @yishayw @Harbs

**Comment by yishayw** [comment]
DragAndDrop is a library that helps drag items in a list to a target list (including DG etc.). DragBead can be attached to controls to make them draggable.

I agree with @mjesteve  about using 3rd party libs.

**Comment by sanjeev-rajput** [comment]
if our (apache royale) primary target is to compile output in JS then we cannot ignore trusted JS libraries or native code of JS available in the present ecosystem. 
Even react and angular have direct support of native JS code that is because of a small group of people cannot compete with the millions of users.

DragEvent class has many events required for D&D but nothing fires. ( i am attaching a mxml file here)

Here is my experience, I am stuck with D&D with apache royale to get done a simple D&D application because half backed native code support and finally i have to give up here.

Here is my suggestion based on my learning.


we have <html:DIV> element support in apache royale including most of other html native elements. Why don't we provide native JS compilation for these elements under COMPILE::JS tag or something similar to this.

Now please, here one can suggest to get this task done in one way or other, but developers loves only if it easier than what is available in the competition or has more supported features with it's own way. 

I also understand the complexity of work and the dedication of the team towards this project so please consider it as a blind suggestion.

And i strongly agreed on give support of 3rd party library wherever it is possible and keep working towards native code.

[dragAndDropPopup.txt](https://github.com/user-attachments/files/19933801/dragAndDropPopup.txt)
