### ISSUE TITLE
ASDoc comments are not available after making an @externs SWC

### ISSUE THREAD

**Issue by jgranick** [apache/royale-asjs#233]
Hi guys,

I am not sure if this is an issue with "royale-js-swf" or with the "ActionScript & MXML" extension for Visual Studio Code. Apologies if this is not an SWC generation issue, but instead is something I should report on the plugin instead.

We have ASDoc comments in our `@externs` classes, but these do not appear in the code editor. Based on the size of the SWC output, I thought this was being stripped out during compilation, but I apologize if I am incorrect. For an external library, including documentation would be awesome to help developers use the library easily :smile:

Thanks :smile:

**Comment by aharui** [comment]
Are you seeing ASDoc for any Royale SWCs?  I'm not sure how code assist in Visual Studio Code works.   AIUI, in Flex and Flash Builder, you could create "Fat SWCs" with ASDoc DITA files in it.  We have not fully completed DITA output.  Royale ASDoc is being handled as a Royale app with JSON instead of DITA files but I don't know if the new IDEs have integrated that.

**Comment by Harbs** [comment]
@joshtynjala Any thoughts on this?

**Comment by joshtynjala** [comment]
I couldn't find any code in the Royale compiler that could parse the DITA format, so VSCode cannot yet display asdoc from *.swc* files. At the time, it can only display asdoc from *.as* files.

**Comment by aharui** [comment]
@joshtynjala How would you like SWC deployment to work regarding ASDoc and debuggable source code?  In Flash Builder, debuggable sources are deployed separately from the SWC and you have to manually set the association from the SWC to the folder of sources (which is rather painful, IMO).  But if you have the sources, then in theory the ASDoc is available there but needs to be parsed from the sources.   Royale can produce JSON files containing ASDoc data.  Those could be deployed separately or added to a SWC as a "Fat SWC".  Sources could also be added to SWCs so they don't have to be deployed separately.

@piotrzarzycki21 Does Moonshine have a plan for handling ASDoc and debuggable source deployment for SWCs?

**Comment by joshtynjala** [comment]
> How would you like SWC deployment to work regarding ASDoc

Ideally, I'd like to be able to support existing SWCs built with Apache Flex that contain asdoc data in DITA format.

Using a different format for Royale is fine, though. Some kind of fat SWC would probably be easiest, so that users don't need to manually associate a SWC with external files.

> In Flash Builder, debuggable sources are deployed separately from the SWC and you have to manually set the association from the SWC to the folder of sources (which is rather painful, IMO).

For SWF debugging, I figured out how to automatically detect the debuggable sources for SWC files -- as long as they are from one of the projects inside the SDK. The debugger exposes the original path to the *.as* or *.mxml* file when stopped at a breakpoint/exception. I think it's the absolute path on the machine where the SDK was built, but as I long as it contains */frameworks/projects/*, I can usually find the local file by replacing the beginning of this absolute path with the path for the SDK on the local machine.

If the path reported by the debugger is not in the SDK, then I try to use that path without any modifications. In other words, it works if the SWC was built on the local machine and the original source file hasn't been deleted or moved. However, if someone downloaded a SWC from a third-party, then there's no mechanism in VSCode for associating debuggable sources with that SWC. I don't really have plans to add something like that right now.

**Comment by aharui** [comment]
The Flex compiler would output DITA, but I don't think it ever parsed it.  I think there were XSLT transforms to generate the HTML for ASDoc web pages and I suspect that Flash Builder had its own parser written in Java when pulling DITA files from a Fat SWC.  I don't know if the format is documented.  You can generate a pile of DITA files by using the Flex MXMLC on the Flex SDK sources with the -keep-xml="true" option.

Generating DITA looked painful so in Royale we opted for JSON.  Also, Royale organizes the JSON files a bit differently to optimize for lazy downloading at startup for the Royale ASDoc app.  And because the Royale ASDoc app is written in AS, I figured JSON might be faster than XML parsing.  So, if you can get VSCode to handle JSON in Fat SWCs that would be helpful since the Royale compiler can generate JSON for ASDoc.  The Royale ASDoc app and JSON files are in the royale-website repo.

**Comment by joshtynjala** [comment]
As I understand it, the DITA format is standardized and documented:

http://docs.oasis-open.org/dita/v1.2/os/spec/DITA1.2-spec.html

Regardless, looking at the output produced by -keep-xml, I would be able to figure out how to parse it without a spec. It'll just take some time.

When I was looking for a DITA parser in the Royale compiler, I found a few interfaces that the SWC reader seems to use to return the raw DITA data from the SWC:

IPackageDITAParser
IDITAList
IDITAEntry

There are no implementations besides an empty one that always returns null, but these seem to be how I could gain access to the raw data embedded in the SWC. There's a method on IASDocDelegate named getPackageDitaParser() that returns the IPackageDITAParser implementation.

For fat SWCs with JSON, it would probably make sense to add some kind of getJsonParser() to IPackageDITAParser that works similarly. Or maybe create an IPackageDITAParser2 so that existing implementations don't need to be changed.

**Comment by aharui** [comment]
When I read the DITA spec quickly a while back, I was left with the impression that it doesn't define the file format for the content as much as it defines a protocol or convention of tag and attribute names when describing content in XML.  So I am glad you were able to determine how to decipher the files.

The compiler-jx project is picking up JS files from the js/out or externs/ "folders" in a SWC.  AIUI, a Fat SWC stores DITA files in an asdoc/ folder.  I haven't actually seen any Fat SWCs to verify that.  I've just deduced that from scraps of internet articles.  The Flex SDK doesn't create or deploy Fat SWCs, AFAIK.  Flash Builder bundles the DITA files separately.  AIUI, the Fat SWC was conjured up for third-parties.  Maybe you can find a pre-existing Fat SWC for a third-party Flex library somewhere on the internet.  But whether you create implementations for the interfaces in the compiler or just open the SWC as a zip file is up to you.

If we do create Fat SWCs with JSON for the ASDoc, I think we'd just stuff the files in there via Zip.  Not sure if we really need a whole interface implementation for it.  I suppose we could create one, but it seems easy enough to just use existing Zip libraries.
