### ISSUE TITLE
(Feature Request) Support -external-library-path using royale-js only

### ISSUE THREAD

**Issue by jgranick** [apache/royale-asjs#237]
Thanks to your guys help, we are generating extern SWC files using `royale-js` rather than the `royale-js-swf` package, which has been great -- it installs over CI and automated builds properly, is much smaller, and is closer to our goal -- JS only. Today I noticed one issue, though, building an SWC for a library that relies on a second library. Use of `-external-library-path` triggers the "Warning: Missing built-in Object" message and does not build. I assume that this is because the argument requires the `royale-js-swf` package (currently), but it would be really nice if there was a way for it to work without.

Another option would be something like `-external-source-path` to note a directory of files to use for completion, but not to compile into the SWC. As we have sources and an external SWC available, this would also work for us to exclude these types in the child SWC.

I'm happy to help more if my explanation did not fully make sense, or if there's a way to use the compiler I'm missing 🙂

**Comment by aharui** [comment]
There are now platform-specific parameters in the compiler.  So not just -library-path, but now also -swf-library-path and -js-library-path.  Same for -external-library-path, -swf-external-library-path, -js-external-library-path.  As you probably can guess, that allows specification of different SWCs per platform.  That turns out to be important for using airglobal.swc for SWF and js/libs/js.swc for JS.

The logic in the compiler says that when compiling for SWF, if -swf-library-path is used, then ignore the plain -library-path.  Same for JS.  Not sure if that's the best decision, but is how it works today.

So, good or bad, that means you have to consistently use the same parameter in all specifications of your libraries.  If you are using frameworks/js-config.xml as a default config, you have open it up and look to see how it specified js/libs/js.swc (which contains the Object definition for JS).  Did it use -external-library-path or -js-external-library-path?  And then you have to use the same parameter for your "second library" and you have to use += to append your second library otherwise you will be telling the compiler to only use your second library and not js/libs/js.swc.

That's the long way of telling you that I'm guessing that you just have to get your compiler options right and it should work.  If you are still stuck, post your full set of compiler options.

**Comment by jgranick** [comment]
Thank you!

Is there a Slack, Discord or other chat I could be using as we work through these issues? It was `-external-library-path=` instead of `-external-library-path+=` that caused this issue. I'm afraid that maybe I'm causing too much noise. Issue closed, thank you again :smile:

**Comment by aharui** [comment]
It is better that we keep using issues or email.  Apache likes things to be archived and open, asynchronous communications.  If we happen to be working at the same time, we can use Adobe Connect for really high-bandwidth discussions, but then those need to be summarized in email later.
