### ISSUE TITLE
api doc is incomplete

### ISSUE THREAD

**Issue by Incubatio** [apache/royale-asjs#299]
I was looking for org.apache.royale.utils.Language.Vector but apparently apache.royale.utils.Language doesn't exists.
I tried on http://royale.apache.org/asdoc/, but maybe it somewhere else.

Side Notes:
- having the top left frame and the right frame allowing to select the content of the bottom left frame feels unintuitive. (maybe just let the right frame empty)
- The search bar is also a bit frustrating, try to search for Vector and see how it reacts.

**Comment by Harbs** [comment]
It's in the Language project.

Royale is broken up into separate projects to make it possible to have different dependencies.

`Language` is missing because it's a Javascript-only class. We don't yet have a way to display JS-only vs SWF-only classes in the ASDoc app.

The ASDoc app needs a lot of work still, but we have limited manpower. We're always looking for volunteers.

Thanks
