### ISSUE TITLE
Error: roBasic.f_GetAppMenus.addEventListener("result", fn_AppMenusRH);

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#355]
i am setting a remoteobject in my main application file

roBasic.f_GetAppMenus.addEventListener("result", fn_AppMenusRH);

I got an error on console :
{onDisposeCallbacks_: undefined, eventTargetListeners_: Object, actualEventTarget_: Object, parentEventTarget_: null,
 org_apache_royale_events_EventDispatcher__dispatcher: Object, …}             Language.js:238
TypeError: this.roBasic.getProperty(...).callProperty is not a function               shmApplication.js:705
TypeError: msg.headers is undefined                                                               AMFChannel.js:260

**Comment by aharui** [comment]
How is roBasic defined?  How is f_GetAppMenus defined?  Please provide snippets of your source code.

**Comment by pashminakazi** [comment]
roBasic is defined as:
<mx:RemoteObject id="roBasic"
						 destination="shmBasic" fault="fn_HandleFault(event);"
						  endpoint="http://localhost:8080/SHMA/messagebroker/websocket-amf"
						 result="fn_roBasicConfRH(event);"/>
Calling java side  method using RO:
roBasic.f_GetAppMenus.addEventListener("result", fn_AppMenusRH);

java side method is defined : 
public Sring f_GetAppMenus(....){....................}

RO Result Handler is :
private function fn_roBasicConfRH(e:ResultEvent):void
{ .......
}

**Comment by aharui** [comment]
roBasic is a RemoteObject which is a Proxy, so in Royale you will have to cast to an Operation like this:

(roBasic.f_GetAppMenus as Operation).addEventListener("result", fn_AppMenusRH);

**Comment by aharui** [comment]
Any errors in the console?  Calling addEventListener doesn't call the server, it only waits for a result.  Some other code has to call the server.  Is that code working?  Are you still using ClassAliasBead?  I think that is required.

Otherwise, use the debugger to step into the call and compare to a working example.

**Comment by alinakazi** [comment]
No error on Console . Yes we are calling this method  this way for the server call: 
roBasic.f_GetAppMenus(...); 
Before that , parentApplication property is working correctly in case of Royale?
Because we find we are calling some methods using parentApplication.methodName(..)
But these method aren't called. So , i just need to confirm that parentApplication property is fully functional ?

**Comment by aharui** [comment]
I recommend that you learn how to use the debugger to answer questions like this yourself instead of having to wait for someone to answer it for you.  There is no way for me to remember if something should be working and I can't always tell by looking at the code.  By stepping into the code, you will see what code is actually running and whether it does something reasonable.

Another strategy is to build a simple test case to see if something works without a lot of other code possibly interfering.

**Comment by alinakazi** [comment]
This is example to test menubar working with XMLList  : https://github.com/pashminakazi/Issues/tree/master/Helloworld

data is successfully retrieved from server side and assigned successfully to menuDataProvider.
But that menuDataProvider is when assigned to dataprovider property control of type mx:MenuBar .
It does not show any output on browser.

We have test a related Example in tourdeflexModules , It also shows nothing on Browser https://github.com/apache/royale-asjs/blob/develop/examples/mxroyale/tourdeflexmodules/src/mx/controls/MenuBarExample.mxml

**Comment by alinakazi** [comment]
Alright, Thanks.

**Comment by alinakazi** [comment]
Set dataProvider is copied from mx/controls/listClasses/ListBase.as to  mx/controls/MenuBar.as and For MenuBar in MXRoyale/src/main/resources/defaults.css IDataProviderItemRendererMapper is now as it is in List.
Still Both examples shows blank output on browser.
Commits added to Royale SDK.

**Comment by aharui** [comment]
Debug into it.  It should be roughly similar to List.  The dataProvider is read, renderers are created.
