### ISSUE TITLE
mx:StringValidator doesn't work 

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#374]
I am Using StringValidator like this
<mx:StringValidator id="vldCode" source="{ci_Code}" property="text" required="true"/><mx:StringValidator id="vldDesc" source="{ci_Name}" property="text" required="true"/>

I also Compiled Tourdeflex StringValidator Example it doesn't work

**Comment by aharui** [comment]
StringValidator looks to be simple enough for you to fix yourself.

**Comment by aharui** [comment]
The general principle for UIComponent subclasses is described here:  https://github.com/apache/royale-asjs/wiki/emulation-components#getting-an-emulation-component-to-run

In the case of StringValidator, since it isn't a UIComponent, I would start by uncommenting the code paths that your application needs.  If it doesn't compile because of some dependency on something that isn't yet emulated, tell us what that is.  We may decide to add that missing dependency to the emulation, or comment it out again, or replace it with something else.

Once it compiles, if it doesn't work, use the browser debugger to figure out why.  It is a good skill to be able to debug other people's code and know how to use tools like debuggers.
