### ISSUE TITLE
Cannot find Vector.<T> methods

### ISSUE THREAD

**Issue by jgranick** [apache/royale-asjs#384]
Hello!

Testing the latest 0.9.6 Apache Royale ASJS nightly, I'm getting these runtime errors for the Starling Framework:

![image](https://user-images.githubusercontent.com/833997/51422813-65ce1a00-1b6a-11e9-97d9-96d221cd596e.png)

I also get similar errors for `insertAt` as well.

I can't tell where `Vector` is defined, except this definition I see in "Language.js"

```js
org.apache.royale.utils.Language.Vector = function(size, basetype) {
  size = typeof size !== 'undefined' ? size : 0;
  basetype = typeof basetype !== 'undefined' ? basetype : null;
  var /** @type {Array} */ arr = [];
  var /** @type {Object} */ defValue = null;
  if (basetype == "int" || basetype == "uint" || basetype == "Number") {
    defValue = 0;
  } else if (basetype == "String") {
    defValue = "";
  }
  for (var /** @type {number} */ i = 0; i < size; i++)
    arr.push(defValue);
  return arr;
};
```

Where are `insertAt`, `removeAt` or other `Vector` methods defined? I also see the *.as extern files, which do define the methods, but we have this problem at runtime.

Thank you

**Comment by aharui** [comment]
I'm not sure I followed what you are saying.

For Royale, the compiler can transpile access to Vectors.  The Transpiler theoretically knows when you are accessing a Vector.  Royale has support for Proxy and converts [] access to getProperty/setProperty/callProperty.  Royale does require that access is strongly-typed, so some access will fail until you set the type.  IOW, if foo is actually a Proxy but you told the transpiler it is an Object, then foo["bar"] will not result in code-gen for getProperty/setProperty

The XMLList implementation I think actually sets properties like "0" on the instance so that you can access xmlList[0].

Since Vectors are supposedly never sparse we could have Vector map to some implementation that similarly sets properties like "0" on itself.  If you want to build out and contribute a better Vector implementation to Royale I will do what I can to help.

**Comment by jgranick** [comment]
I would imagine that it would make sense to A.) inline convert `vec.insertAt` or `vec.removeAt` to a compatible implementation for `Array`, but this still does not fix support for `vec.fixed` behavior

The other approach (which we use in OpenFL) is to B.) have a custom `Vector` implementation at runtime. That simplifies the compiler's job, and makes it just rely on a prewritten implementation in JS

**Comment by aharui** [comment]
I assume vec.fixed is the check for writing past the end of a fixed-length vector?

You are correct that mapping to Array wouldn't check for that.  The compiler can can transpile different ways to write something if it knows the types, but it can't tell whether that write is will actually succeed if the Flash runtime was checking the write.  Not only is that true for access "out-of-range" but also I think there were certain runtime checks of the type that was being written to a Vector.

When we first embarked on FlexJS (now Royale) I had in mind that it would be a best practice for the app developer to generate a Flash version of the app that could at least be used for testing because the Flash runtime will do lots of runtime checks that the JS runtimes do not.  Once your Flash version is tested and runs then you know that you are that much safer running on the JS runtime.  I still think that makes sense for really complex apps, although folks will likely be using AIR instead of Flash.

If you can make the assumption that those code paths are "safe" you can, in fact, eliminate a lot of runtime overhead.  Unless your app actually relies on getting a RangeError, hopefully the code paths have been tested so they don't cause a RangeError and then you don't need to run that check for out-of-bounds on every write.

Royale is attempting to be more of a tool-chain/workflow than a framework.  So we can offer different implementations of a Button and maybe we should offer different implementation of a Vector.  We focus a lot on Pay-As-You-Go (PAYG) so if you don't need a check for writing out-of-bounds, Array can be a small/fast substitute for Vector.

But if you need that check then the transpiler could output different code and folks can swap in different implementations of Vector that do more and more runtime checks.

If you want to contribute a Vector implementation for those who need it I think that would be awesome.  Bonus if you can figure out the compiler changes to switch to that implementation.

**Comment by jgranick** [comment]
Porting Starling using Apache Royale will not work properly if `Vector` does not have the same methods or the fixed behavior.

I suppose this does raise some interesting questions -- Haxe supports typed arrays by design, so `Array<Float>` is possible already. In ActionScript, `Vector.<T>` is the only way to get a typed array.

I think perhaps Royale should either 1.) support `Vector.<T>` as is (a map for typed `Array`) and have new SWC externs that match the type, and make sure it's known it is not like the Flash runtime `Vector` type, or 2.) implement a `Vector.<T>` implementation (sort of like the above) and call it a day or 3.) implement a `Vector.<T>` implementation and extend `Array` to support types or create a new `TypedArray.<T>` or `ArrayT.<T>` type of some kind for lightweight types over `Array`

I apologize I cannot contribute more directly. If you guys decide to go for #1, then we'll change Starling to use `openfl.Vector` instead of `Vector` and let it be a separate implementation. This isn't as elegant (and removes the ability to have types), but it would be functional. 

If you decide to go with some variant of #2 or #3, I hope the code I've shared will help :smile:

**Comment by aharui** [comment]
Ok, so to confirm, Starling relies on the exception resulting from trying to write past the end of a fixed length Vector?

I expect we will offer various implementations as they have different size/speed metrics.  I might have time to start on this in February if nobody else beats me to it.

**Comment by jgranick** [comment]
Starling _does not_ rely on the thrown exception. For sure it relies on `vec.length` (from my knowledge) but it _might_ toggle `fixed` properly when changing lengths.

**Comment by jgranick** [comment]
Thank you! This sounds like a good way to start :smile:

For the purposes of licensing, the above code is MIT-licensed, under my name. I, Joshua Granick, provide full and unconditional permission for `openfl.Vector`/`openfl.VectorData` to enter the public domain for complete freedom to re-license.

**Comment by aharui** [comment]
OK, sounds like we have a plan.  I should have bandwidth to respond to problems related to Vector in the compiler, although it would be in your best interest to learn how to patch the compiler yourself.

Regarding licensing/copyright:  I am not a lawyer, but as I understand it, "Public Domain" is an actual thing different from the MIT License.  The MIT License is sufficient for Apache projects to work with your code, so no need to further enter it into the Public Domain.

The main issue regarding your code is whether it is treated as "contributed to Apache" or "third-party".  To contribute that much code to Apache, you would probably have to sign an ICLA.  To treat it as third-party and bundle in a release means we have to list it in some other "notice" files and preferably alter the build scripts to download the original from your repo.  I want to punt on all of that paperwork for now, work with you to get Vector working, then see whether bundling makes sense or not.  (BTW, I haven't looked in your repo, but hopefully the actual file has a header as required by the MIT License)

Eventually, like I mentioned, it would be good for you to learn how to change our code and even become a committer so you can rely on Royale without concern about who is around to fix bugs and make releases.  But that can happen later.

**Comment by greg-dove** [comment]
FYI I expect to push a new evaluation branch in a couple of days with improved Vector support. More information to follow when I do that...

**Comment by greg-dove** [comment]
Just quickly (as it is the end of my day)
I pushed a branch called improvements/Language
It has what I think it reasonably robust support for Vector - I started from scratch and did something more in line with what I think we need, using an approach that also supports some other 'lite' types, but I am still working on some fine tuning
All the unit tests below this line here work correctly (correspond to AVM in swf):
https://github.com/apache/royale-asjs/blob/improvements/Language/manualtests/UnitTests/src/main/royale/flexUnitTests/language/LanguageTesterTestVector.as#L65

It does not support length setter checking and index checking via dynamic/untyped access, because that functionality is all compiler driven thus far. But most other things will work at runtime even when typing is obscured. In the future (or even now) it will be relatively simple to switch to full runtime support for length setter and index checking aspects with es6 Proxy (IE11 is the only meaningful target that does not support this, I think).

Note that the tests marked with [TestVariance] metadata do have inconsistency to AVM. A couple of these are intentional based on switching off the compiler support for index checking of assignmnents, which mean that the out of range errors are not thrown. The constructor one seems relatively unimportant I think.

@aharui Alex: I don't think the idea of custom alternate Vector implementations makes sense longer term. Vector<> is an actionscript language type/feature - like Array or Number or XML etc. The possibility of conflicting implementations of a core typing aspect of the language does not make sense imo. Plus the generic aspects of this mean it does not behave like a regular class (and in fact there are some specific rules for *is* and *as* checks that could make it difficult to get it working right with emulation classes quite apart from the issues of compatibility between implementations). 
So I think we should stay with a single conforming implementation, but with the possibility to explicitly improve performance once safety is assured with code that uses it.  The obvious standout here to avoid performance issues is the index level checking for assignments. Maybe it is possible to sense that the code is inside a correctly constrained loop, but that seemed a little tricky for now, so it does need manual switching. I switched the index checking off in all the framework projects. 

As I said, I am still working on a few bits of tuning, but I hope it could be ready to merge to develop within a week. Meanwhile I'd be keen for folks to try things in the branch and let me know of any issues before then ...

**Comment by aharui** [comment]
IMO, a single Vector implementation is not PAYG.  If I just need one 4 element Vector<uint>, how much code is that going to cost me?

Ideally, the compiler would output the correct set of information the implementation needs, and different implementations could optimize as needed.  I think that's how E4X is proposed in the ECMA spec and implemented in Royale.  Various E4X syntax in AS ends up as low-level calls to the E4X implementation.  I am hoping we can do something similar for Vector.

Some Vector implementation like the one you are working on can be the default, but there should be a way to get cheaper implementations if you need them.

**Comment by greg-dove** [comment]
> IMO, a single Vector implementation is not PAYG. 

There is no reason it need not be. It just needs to be able to be tuned/scalable in terms of trade-off between type safety and performance. IMO a single implementation that supports performance tuning is more logical than introducing inconsistency and incompatibility to achieve performance tuning, *especially* for a core language feature. When I check if the Vector.<IBead> that was created in the framework is the same type as the Vector.<IBead> that I created locally in my project, they *better* be the same actual type, otherwise I no longer have faith that this 'actionscript' is really actionscript - because it is not behaving according to spec.
I think framework component sets can and should be PAYG in terms of the way you think about multiple alternate implementations.
But this is *Language* - it is a core part of actionscript and is specified.
In that sense Vector is not different to Array or Number or String, imo. 
Either the js target behaviour meets the specification or it does not.
I'm not sure about your point with e4x. We have a reference implementation that is defined for actionscript - I presume that has also been the goal to match as a standard (fyi OT: I do have a minor XML fix coming too I think, still working on it)
Languages like Haxe which have multiple (8+) targets have to do this stuff well - almost *everything* in the standard library for Haxe is unit tested so that each target conforms  - and it makes it much easier to introduce new targets, and consistency across targets is assured because they conform to the language spec. Of course, Haxe (as a custom language, for example) has the luxury of defining certain things as explicitly 'unspecifed' behaviours, such as default initializer values...  in royale we do not, because we have a core language specification already (and a reference implementation in flash player to compare against, that serves to fill in any gaps in the spec). We are obviously adding to that specification (Josh's language additions), but I don't expect the plan is to remove things from it...

I'm sorry Alex, but your 4 element Vector example made me laugh - maybe you want to reconsider whether that is a realistic challenge! :)
If I only needed one four element Vector, I would really be asking myself why do I need that? - especially if I knew it was not something with native support on the target platform.
Certainly if it was the only Vector I was using and absolutely necessary then I must *really* want it to be exceptionally Vector-like, otherwise I would use an Array! In that case I would be happy to pay the price.
On javascript you won't be saying to yourself: I am going to choose Vector because it's more performant than Array. But type safety is one of the primary premises of why you would choose the Vector type, so it seems like that is the starting point. 

My goal is certainly to have this as a default implementation, but to be able to tune it down (or switch certain things off with compilation flags or local doc directives). In other words: support opt-in performance tuning ('pay' less), but keep some low level consistency that allows aspects of the typing checks etc to still work properly. 

Anyway, if you get a chance please give the branch a try, and let me know what you think after trying it.

**Comment by aharui** [comment]
I object to the tone of your response.  Belittling my question is not the style of technical debate I think we should be promoting.  We just saw that we could not convince new volunteers to help with the docs.  Knowing you might get belittled is not going to encourage people to contribute.

If you want to have a technical debate, let's discuss the technical aspects without attacking people or their ideas.

**Comment by greg-dove** [comment]
Alex, I'm sorry you feel that way. It was intended to be light-hearted, not 'belittling'. I did think your question/example was not realistic, and I was hoping that you might take a step back and maybe see it the same way if you looked at it from a different perspective, but I was not intending to offend in any way. I am keen to discuss the technical aspects, but I will open a thread about that in the future, and certainly will welcome your input.

**Comment by carlosrovira** [comment]
Hi Guys, I know to what Alex refers, and as I read it, I know it will make him upset. 

If it can help, I know for sure that it was not the intention of Greg. And sometimes the choice of words is unfortunate, so hope Alex can forgive this little mistake and could continue with this thread that I think is very interesting, this could happen to any of us.

I understand that Greg has worked heavily latest weeks in this change, that seems to me an important and complex one, and is normal that he want to expose all the things he saw when working over it since that makes him to have deep knowledge, so it can be frustrating when others don't see the problems exposed.

Thanks and please let's go! :)

**Comment by aharui** [comment]
IMO, this is a reminder that our communication systems (email, bug reports) is low-fidelity, so we have to be extra careful with our words.  Please edit your post (I think you only have to remove one sentence).  I prefer that we do not leave as precedent sentences that can be misinterpreted.

I do want to thank you for your efforts on having at least one solid Vector implementation and lots of tests for Vector and other language issues.  

I will be distracted with some non-work stuff this week so I may be slow in continuing the technical discussion.

**Comment by greg-dove** [comment]
Sure, thanks for your understanding and once again, sorry for creating the wrong impression here. The activity I described was a friendly one in my mind, not a derisive one, and I had added a smiley etc to try to convey that. But I agree, it is not a good medium for expressing things in that way. I edited it out, and will avoid this type of thing in all future communications.

**Comment by greg-dove** [comment]
@aharui , I'll copy/paste your latest comment and respond inline in a dedicated discussion on dev list tomorrow. This issue is closed and we are OT on the original issue now. My main aim was to ping Joshua Granick with my first main update earlier (I hoped he might be able to test and provide feedback from the branch too, Starling will be a good thing to get right for performance tuning). Anyhow, I should have started something new for our discussion - my fault. Let's do that beginning tomorrow (understanding that you sound busy for a while, so just whenever you can get back to it).
