### ISSUE TITLE
RemoteObject Issue

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#387]
Hi,
In my Project, I have ActionScript file which calls 7 or 8 Java side functions of the Same File.
Only one function not called.
I have created a paste of some of my code: https://paste.apache.org/rxiV
roBasic.getAppParams called but roBasic.getUserParams not called why?

**Comment by carlosrovira** [comment]
Hi Alina, don't see any problem in your code.
I think @greg-dove talked about some issues in batch calls, but I think you're working with simple calls like the ones we are doing in our project, so maybe you should try to debug the code and see what happens. Or try to put buttons temporaly that will call each method one by one and see things are sending and coming. I recommend you to use Charles App (or other with AMF support) to see the traffic going and coming and check things are ok until you found where the problem is located
