### ISSUE TITLE
AdvancedDataGrid won't work with Different Kinds of Data

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#391]
I am unable to fix CapsLock.
And I am using AdvancedDataGrid in my Application
File: https://paste.apache.org/gYvR
Data which is Returned From Java Method is of (VO) type

public List < shmCompanySetupVO > fn_GetCompListDP()

So AdvancedDataGrid doesn't set the data
https://user-images.githubusercontent.com/42200979/51969447-3c7c8a80-2496-11e9-80c3-3ae9a3eb2c80.png

**Comment by aharui** [comment]
Can you reproduce the problem in a simple example?  Maybe modify the ADG example in Tour de Flex to use samples of your data?

**Comment by pashminakazi** [comment]
https://paste.apache.org/gYvR
This is TDF example I have added RemoteObject and Our Application's Data in That file But It doesn't set the Data.
Data Returned From Java Method is : [ com.shm.VO.Common.shmCompanySetupVO@1b7908ed ]

**Comment by aharui** [comment]
A simple example would not need RemoteObject.  It would just instantiate a bunch of the VO classes with some data and add it to the same sort of data structure so others can run the example without needing access to the RemoteObject server.

**Comment by aharui** [comment]
Please open a separate issue for CapsLock.  I think I have it working on my computer.  I will commit those changes after you create a separate issue and go back and review your other open issues and close the ones that are no longer needed.

**Comment by pashminakazi** [comment]
Ok. I will open a separate issue for CapsLock

**Comment by pashminakazi** [comment]
I have Created an Example: https://github.com/pashminakazi/AdvancedDataGrid

**Comment by aharui** [comment]
That link has a RAR file.  I cannot open the RAR files from you or Alina.  I really only need the two or three source files.  If your example has more than that, it might not be simple enough.

**Comment by pashminakazi** [comment]
HelloWorld.mxml : https://paste.apache.org/UdKd
shmCompanySetupVO.as : https://paste.apache.org/8nko
Welcome.mxml : https://paste.apache.org/vIQL
I Don't want mx: Grouping in Welcome.mxml, but I add it to show some Data in Example.
Because Without mx : Grouping i am unable to show Data in AdvancedDataGrid
Please make this Example working

**Comment by aharui** [comment]
Does it require a Module like Welcome.mxml to make it fail?  Otherwise, simplify more.  Try to get it down to one MXML file.  The more complex the example, the longer it will take to figure out the problem.  Do not use Grouping if isn't being used in your app.  The tags in AdvancedDataGrid should closely match your app.

**Comment by pashminakazi** [comment]
Now I have Only One mxml File And I remove mx: Grouping 
I have been Working on AdvancedDataGrid From last 15 days But i Couldn't find the Problem Please Find the Problem
HelloWorld.mxml : https://paste.apache.org/ruYm
shmCompanySetupVO.as : https://paste.apache.org/47uj

**Comment by Harbs** [comment]
Shouldn't it be: `dataProvider="{arcCompData}"`
instead of: `dataProvider="arcCompData"`

**Comment by pashminakazi** [comment]
Yes, It should be: dataProvider="{arcCompData}"
Thanks

**Comment by Harbs** [comment]
Does that make it work?

**Comment by pashminakazi** [comment]
No,
If I manually insert Data into AdvancedDataGrid or Data Retrieved From VO class.
In both Cases it doesn't show the Data

**Comment by pashminakazi** [comment]
Please Help me in AdvancedDataGrid and Capslock 
I have to show my Work to the director of my Company

**Comment by aharui** [comment]
Pashmina, I will help you, but you must also help us.

I just looked and there are a lot of issues opened by you and your co-workers.  Please close any that are no longer relevant.  Please confirm in a comment on this issue that you understand what I am asking you to do for the second time.  You should be able to see the list of issues by clicking the issues tab or this [link:](https://github.com/apache/royale-asjs/issues)  Once I see that you have closed issues or added comments to the ones that are still relevant that explain why they are still relevant, I will commit the caps lock code.  If you do not clean up your issues, we spend extra time reviewing these issues and have less time to help you with really important issues.  

The same is true for the test cases you submit with these issues.  They must be simple otherwise it will take us longer to help you and we won't have time for more important issues.  You will probably find this to be true when working with other teams and companies someday.  It is good to get into the habit of efficient and effective communication.

Your director is welcome to have a conversation on our dev@ list or with me directly if they have concerns about the choice to use Royale or the process of finishing your application.  I think there is a communication problem that is causing inefficiencies.

**Comment by aharui** [comment]
I have this fixed locally.  Clean up your open bugs and I will commit this fix.

The key factor was that the data is not hierarchical.

In the future, please include in the comments if you are getting runtime exceptions or not.

**Comment by pashminakazi** [comment]
Thanks, Alex
I Closed my Issues, those are solved

**Comment by pashminakazi** [comment]
In this Example, There are 2 AdvancedDataGrid.
I have inserted Manual Data in 1st AdvancedDataGrid and In Another AdvancedDataGrid, Data is Retrieved from VO class 
![image](https://user-images.githubusercontent.com/42200979/52695499-8a14ef00-2f8e-11e9-8315-040dfd391275.png)
Still not showing Data
HelloWorld.mxml : https://paste.apache.org/hkmW
shmCompanySetupVO.as: https://paste.apache.org/k4qI

**Comment by piotrzarzycki21** [comment]
@pashminakazi can you make something like that and say whether it's working ?

```
<mx:AdvancedDataGrid id="myADG2" x="200"
            width="40%" height="40%" dataProvider={Manual}>
            <mx:columns>
                <mx:AdvancedDataGridColumn dataField="ci_Name" headerText="Name"/>
                <mx:AdvancedDataGridColumn dataField="ci_Code" headerText="Code"/>
            </mx:columns>
</mx:AdvancedDataGrid>
```

**Comment by piotrzarzycki21** [comment]
@pashminakazi did you rebuild your SDK with Alex's fix ?

**Comment by pashminakazi** [comment]
@piotrzarzycki21 I tried it But Nothing Happens

**Comment by pashminakazi** [comment]
@piotrzarzycki21 Yes, I rebuild SDK with Alex's fix

**Comment by Harbs** [comment]
Did you clean your project? Did you check your js file to see if Alex's changes to `hasChildren` and `isItemOpen` are there?

Did you try debugging the code to see what happens?

**Comment by piotrzarzycki21** [comment]
I wanted to try that example, so downloaded Nightly #1952, but I cannot even build Hello World. Do I need to specify something special in order to make it working ? 

```
Compiling HelloWorld
: SDK path: D:\Work\royale_ide\royale_nightly_js_swf
: Using Royale Compiler codebase: D:\Work\royale_ide\royale_nightly_js_swf
: Using Royale SDK: D:\Work\royale_ide\royale_nightly_js_swf
: MXMLJSC
: -sdk-js-lib=D:\Work\royale_ide\royale_nightly_js_swf\frameworks\js\Royale\generated-sources
: -load-config+=obj/HelloWorldConfig.xml
: -compiler.targets=JSRoyale
: -js-output=D:\Work\royale-sources\royale-asjs\examples\mxroyale\HelloWorld
: D:\Work\royale-sources\royale-asjs\examples\mxroyale\HelloWorld\src\main\royale\HelloWorld.mxml(20): col: 1 Error: This tag could not be resolved to an ActionScript class. It will be ignored.
: 
: <mx:Application xmlns:fx="http://ns.adobe.com/mxml/2009"
: ^
: 
```

**Comment by Harbs** [comment]
I think you need a `-flex` compiler argument to load the MXRoyale swc

**Comment by Harbs** [comment]
(Or you can specify the `RoyaleMX` swc directly.)

**Comment by piotrzarzycki21** [comment]
@Harbs do you mean -flex=path to swc ?

**Comment by Harbs** [comment]
No. Look at the examples in the mxroyale folder. They specify `<property name="config_arg" value="flex"/>`

**Comment by piotrzarzycki21** [comment]
Ok ! I had to specify +configname=flex. Thanks!

**Comment by piotrzarzycki21** [comment]
I'm not sure whether my findings are correct but I think we should listen [here](https://github.com/apache/royale-asjs/blob/483887741a55c5e4e1388baf9e75434818e14742/frameworks/projects/MXRoyale/src/main/royale/mx/controls/beads/DataGridView.as#L59) on `model.addEventListener("dataProviderChanged", dataProviderChangeHandler);` In time when we are receiving data AdvancedDataGridColumnList doesn't have assigned yet [adg](https://github.com/apache/royale-asjs/blob/483887741a55c5e4e1388baf9e75434818e14742/frameworks/projects/MXRoyale/src/main/royale/mx/controls/beads/DataGridView.as#L72)

**Comment by pashminakazi** [comment]
HelloWorld.mxml : https://paste.apache.org/nO2o
Please Make this Example Working

**Comment by piotrzarzycki21** [comment]
@pashminakazi you have committer privileges - try debug it in the browser and fix issue. I pointed you that. The only difference which I did for simplicity I'm assigning straight dataProvider in fn_InitModule. Try that and debug to see what is happening. You can take a look into [default.css](https://github.com/apache/royale-asjs/blob/483887741a55c5e4e1388baf9e75434818e14742/frameworks/projects/MXRoyale/src/main/resources/defaults.css#L75) file to see what parts has AdvancedDataGrid and analyze them, setup breakpoints. 
Unfortunately I don't have fee time to do this for you.

**Comment by aharui** [comment]
It was a timing issue with when the dataProvider gets set and what events would update the adg property in the internal lists.  I don't expect Pashmina to be able to debug and fix problems of this complexity now, but am looking for signs that she is learning about the code so that someday she can.  I would like to see indications that she tried to debug into it.  There were clues in the code I changed in the prior commits.  Setting breakpoints there should have helped her make the diagnosis Piotr did (that the adg property as null).  And then the questions she asks will be more specific as in "the adg property is not set, what is a good way to set it" instead of "make this work for me".  Her company should be encouraging Pashmina to learn about the code so they aren't dependent on us.

**Comment by piotrzarzycki21** [comment]
> It was a timing issue with when the dataProvider gets set and what events would update the adg property in the internal lists. I don't expect Pashmina to be able to debug and fix problems of this complexity now, but am looking for signs that she is learning about the code so that someday she can. I would like to see indications that she tried to debug into it. There were clues in the code I changed in the prior commits. Setting breakpoints there should have helped her make the diagnosis Piotr did (that the adg property as null). And then the questions she asks will be more specific as in "the adg property is not set, what is a good way to set it" instead of "make this work for me". Her company should be encouraging Pashmina to learn about the code so they aren't dependent on us.

Completely agree on that. Getting this knowledge would only benefits for her employer.
