### ISSUE TITLE
How To Add Jewell Theme

### ISSUE THREAD

**Issue by angelhdz** [apache/royale-asjs#396]
Hello guys. Working on VSCode. Nextgenactionscript extension.

The components are displayed. The AS3 code works. I can debug.

The only issue is to apply a Jewel Theme. I tried using the bindings:

` <j:Button  text="MyButton" emphasis="{Button.PRIMARY}"/>`

The button stays gray. Tried to modify the CSS directly, but when I compile again, the CSS, HTML, everything gets overwritten.

Any tip so I can finally start building Royale apps? Long time trying to make something and as I can not find anything in the documentation or in the closed tickets, I lose interest.

Appreciate any useful information.

**Comment by piotrzarzycki21** [comment]
Hi @angelhdz ,

The only thing which come to my mind is that you have to add to your asconfig.json in compilerOptions:

`"theme": "${royalelib}/themes/JewelTheme/src/main/resources/defaults.css",`

**Comment by angelhdz** [comment]
Thanks for the fast response Piotr!

I already have that line in the asconfig.json. But when compiling, it looks like the asconfig is being ignored by the Royale compiler or the nextgenactionscript extension. It also ignore the “debug”: false, and still show the Chrome debugger.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by piotrzarzycki21** [comment]
Could you attach your project to this issue, so I could try it out ? Also what version of SDK are you using ? [Nightly build](http://apacheroyaleci.westus2.cloudapp.azure.com:8080/job/royale-asjs/) or Released one ?

**Comment by angelhdz** [comment]
**Environment:**
SDK Version:  0.9.4 (JS & SWF).
Build: Release
IDE: VSCode + nextgenactionscript extension
VSCode version: 1.31.1
OS: Windows 10 Pro 64bit

Issue:

Either Royale compiler or nextgenactionscript are at fault of not loading the asconfig.js file, so it will ignore my _"debug": false_    and   _"theme": "${royalelib}/themes/JewelTheme/src/main/resources/defaults.css" compiler options.

The Jewel themes CSS files aren't loading, so the components look default style.

**Details:**

-The SDK source is on my F: partition. The Jewel themes folder is inside.
- The SDK is successfully added on VSCode.
- Royale application compiles OK.
- In an Adobe AIR Desktop or Mobile workspace, everything works OK. 
- 


Project attached:
[Test.zip](https://github.com/apache/royale-asjs/files/2885044/Test.zip)

**Comment by angelhdz** [comment]
Tried:

`"theme": "${royalelib}/themes/JewelTheme/src/main/resources/defaults.css"`

And:

`"theme": "${royalelib}/themes/JewelTheme/target/JewelTheme.swc"`

No success. I saw a pom.xml and build.xml files. Do I need to make those?

![2019-02-21_08-45-14](https://user-images.githubusercontent.com/10191085/53170652-08891680-35b7-11e9-8517-3b4db8f17202.png)
![2019-02-21_08-44-27](https://user-images.githubusercontent.com/10191085/53170653-0921ad00-35b7-11e9-8685-beb39cabbb21.png)
![code_2019-02-21_08-43-41](https://user-images.githubusercontent.com/10191085/53170656-0921ad00-35b7-11e9-9067-1f11c4d865af.png)

**Comment by carlosrovira** [comment]
Hi,

in button 4 , after PRIMARY there's a missing "}"

I don't know too much about asconfig (just use it to get code hinting in VSCode), but don't see more problems.

You can try as well maven build. Is what I use to build Jewel, JewelTheme and projects like TourDeJewel or our real projects

**Comment by angelhdz** [comment]
I installed maven. Set the environment path. 

Tried to create a project following this guide: [](https://github.com/apache/royale-asjs/wiki/Create-Royale-project-with-Maven)

I got this error:

![cmd_2019-02-21_21-39-40](https://user-images.githubusercontent.com/10191085/53214027-694d3900-3621-11e9-88de-30a09ea14194.png)

**Comment by angelhdz** [comment]
Tried to follow this guide also:

https://www.youtube.com/watch?v=Fcq38JDTtNs

But there is basically non-existent Apache Royal tutorials, guides, steps, etc.

**Comment by angelhdz** [comment]
UPDATE:

Managed to create the Royale simple application project with maven:

The error was due to the archetype version. Replaced the version with the latest Royale version 0.94 and error went way.

**Comment by angelhdz** [comment]
I executed the last command, mvn -s /path/to/royale/settings-template.xml clean install.

The only error was:

>  Could not resolve dependencies for project org.apache.royale.framework:royale-simple-application-archetype:swf:0.9.4: Could not find artifact com.adobe.flash.framework:playerglobal:swc:20.0 in bintray-konsoletyper-teavm (https://dl.bintray.com/konsoletyper/teavm)

So, now what? How do I run this project with Maven? Or do I still need VSCode to compiler it? I don't really understand what Maven is supposed to do.

So much steps just to get Jewel working man. The standard ApacheRoyale compiles OK with VSCode. I just want to apply the Jewel themes!!!!

Please help, I had been months trying to get this work to finally try Apache Royale, and I'm losing interest due to all the headaches it gives to set up.

**Comment by piotrzarzycki21** [comment]
> Tried:
> 
> `"theme": "${royalelib}/themes/JewelTheme/src/main/resources/defaults.css"`
> 
> And:
> 
> `"theme": "${royalelib}/themes/JewelTheme/target/JewelTheme.swc"`
> 
> No success. I saw a pom.xml and build.xml files. Do I need to make those?
> 
> ![2019-02-21_08-45-14](https://user-images.githubusercontent.com/10191085/53170652-08891680-35b7-11e9-8517-3b4db8f17202.png)
> ![2019-02-21_08-44-27](https://user-images.githubusercontent.com/10191085/53170653-0921ad00-35b7-11e9-8685-beb39cabbb21.png)
> ![code_2019-02-21_08-43-41](https://user-images.githubusercontent.com/10191085/53170656-0921ad00-35b7-11e9-9067-1f11c4d865af.png)

@angelhdz On your screenshot I see that you successfully displayed Jewel Theme, are you trying to display different theme ? Different colors etc ? I'm confused.

**Comment by angelhdz** [comment]
Yes I'd like to have the colors shown in the Jewel demos!

![chrome_2019-02-22_04-11-53](https://user-images.githubusercontent.com/10191085/53228624-278bb500-3658-11e9-94a1-b04ae95c8caa.png)

**Comment by angelhdz** [comment]
So finally you made me realize the themes are being applied. But not the **colors** of the buttons and other components. Do I need it to specify the colors with AS3 code? Or MXML tags?

**Comment by piotrzarzycki21** [comment]
I'm looking into that. First of all I think your asconfig should looks like that:

```
{
    
    "compilerOptions": {
        "debug":  false,
        "source-map": true,
        "theme": "${royalelib}/themes/JewelTheme/src/main/resources/defaults.css",
        "targets": [
            "JSRoyale"
        ],
        "source-path": [
            "src"
        ]
    },
    "files": [
        "src/HelloRoyale.mxml"
    ],
}
```

**Comment by carlosrovira** [comment]
Hi Angel, 

ok, so you have part of the JewelTheme working, so let's try to find why you don0t get colors.

Some concepts to take into account. JewelTheme are really 3 themes in 1. So we have 'default' color (light or dark) and 'primary' in the main one, and other for 'secondary' and other for 'emphasized'.

Then people could use JewelTheme that is the master theme capable to generate in just one css all 3 themes styles.

Other people would want to just use themes distributed with Apache Royale. Here we will have all combinations based on 12 different colors (around 170 different theme combinations).

Looking at the example in TourDeJewel (TDJ) pom.xml, we are using the master theme and you'll see:

`<dependency>
      <groupId>org.apache.royale.framework</groupId>
      <artifactId>JewelTheme</artifactId>
      <version>0.9.6-SNAPSHOT</version>
      <type>swc</type>
      <scope>theme</scope>
      <classifier>js</classifier>
    </dependency>`

This is the master theme, and that is sufficient. changing vars inside, the SASS compiler generates all the styles. So if you change vars in this theme you need to compile de SASS to get the final CSS. Notice that only in Maven we have a task that uses CSS. As today nobody has setup something like that in ANT yet.

after that, we have commented the following code in the pom.xml:

``

If you comment the JewelTheme and uncomment this maven config, you'll get the specific themes:

- Jewel-Light-NoFlat-Primary-Blue-Theme
- Jewel-Light-NoFlat-Secondary-Topaz-Theme
- Jewel-Light-NoFlat-Emphasized-Emerald-Theme

Those are the Apache Royale distributed themes with the generated CSS ready to be used. 

All three themes are for Lifght (grey) and no flat styles, and the first one is for primary blue colors, the second is for get secondary topaz (like an orange) styles and the final is for an emphasized emerald (like a green-yellow) color.

You can put *all* this three css file themes in your config and that should make it work and get all styles.

Let us know If that make it work.

btw, maybe the problem that you don't get colors in your try is because they only are generated using MAVEN since there's no ANT task for this. Other way to get those styles directly is with the released SDK.

HTH

Carlos

**Comment by piotrzarzycki21** [comment]
@angelhdz I got it working, so I will attach example here so you can see what has happened.

**Comment by piotrzarzycki21** [comment]
Here you have examples attached. What has changed:
1. You should use html template which is in every example for Jewel. I added that template in src/resources folder and used options in compiler to load it. 

`"html-template": "src/resources/index-template.html",`
2. I'm not sure why but this is probably bug, but if you specify binding bead on the level of application it simply doesn't work. I have create separate view called `MainView` and place your code there along with usage `ContainerDataBinding`

Take a look into asconfig.json and code in general. It should gives you good starting point. Btw I was using [Nightly Build](http://apacheroyaleci.westus2.cloudapp.azure.com:8080/job/royale-asjs/)

[TestAngelhdz.zip](https://github.com/apache/royale-asjs/files/2893068/TestAngelhdz.zip)

**Comment by angelhdz** [comment]
***While typing this message I noticed you replied again with a successful project. I will check it up.***

Thank you for replying and for your time, Carlos.

I really don't wish to use Maven. I'm used to ANT with AIR. Never used Maven before.

So,  I switched to **JewelTheme** instead of  **Jewel-Light-NoFlat-Primary-Blue-Theme**. 

Also I know what SASS is, but I don't want to use it. I just want a simple way of building an HTML page or app with Actionscript 3.0 and MXML. So I just chose the already made defaults.css files.



![code_2019-02-22_04-39-33](https://user-images.githubusercontent.com/10191085/53229929-e09fbe80-365b-11e9-9ed3-b398c678a115.png)

**Comment by angelhdz** [comment]
Oh God! Finally **COLORS**!!!!!!!!!!

Now I will look at the rest of the files to see what changed. For now, all I've seen that changed was the use of :

`<js:ContainerDataBinding/>`

And:

`<j:ApplicationResponsiveView>` 

And 2 added files:

**app-styles.css** and  **index-template.html**.

Can you please confirm that these 4 modifications are what got it working?




![Uploading chrome_2019-02-22_04-50-15.png…]()

**Comment by angelhdz** [comment]
### SOLVED

Finally found what really makes the colors to show:

` <j:beads>
        <js:ContainerDataBinding/>
    </j:beads>`

Without these lines, there are no colors.

I will read the doc to understand **Beads** and **ContainerDataBinding**.  At least I know what ContainerDataBiding does because I use bindings in C# with WPF.

Beads are new for me.

### FINAL WORDS

I really, really appreciate your time and kindness Carlos. I usually solve my issues myself. I taught me AS2, AS3, Python, C#, PHP. But it's using libraries and setting up configurations what's the most hard process.

I will donate at the end of the month when I get paid at my freelance landscaping job (I used to work as programmer but after Hurricane Maria here in Puerto Rico, I had to move on. Now programming is like a hobby, but I still wish to make some worthy apps and games in the upcoming years.)

Sincerely, 

Angel

**Comment by carlosrovira** [comment]
Hi Angel,

ContainerDataBinding is what makes data binding work. In Royale, binding is not setup directly as in flex to get a better performance. Binding is "composed" and you put it when you really needed. But if you come from flex, you must to have it always in mind, since you can put a binding and it doesn't work until you remember that you forgot to set up the binding bead ;).

Finally great to have it working. We need people like you that likes Royale and could understand how to work with it. And eventually contribute to the project make it grow more a more. For example contribute docs, tutorials, and more. We should as well to start moving the tech in stackoverflow so people starting with Royale can get answers in that kind of sites.

So you're welcome and to contribute as you want :)

**Comment by angelhdz** [comment]
Yeah, never worked with Flex. I tried it, but at first I didn't like the mxml syntax, until I saw that every language (C#, Python, etc.) started to use XML to build the components.

I'm used to create everything with code, that's why I so loved Feathers until I learned Adobe stopped supporting it. :(

**Comment by angelhdz** [comment]
### Hello again! I hope you are doing great.


I decided to try Royale again... 

I had issues with Jewel themes again, using the databindings. 

If I use the string equivalents, it works:

`				<j:Button text="Primary" emphasis="primary"/>
`

But when I use the databinding, it doesn't work:

`				<j:Button text="Primary" emphasis="{Button.PRIMARY}"/>
`

So I decided to download the sample file you sent me and it worked.

Then I realized, in order for it to work, the buttons must be in a separate MXML file.

If I place all the code in the main MXML file, it stops working, no Jewel Themes.

Why is this happening if I have the `<j:beads><js:ContainerDataBinding/></j:beads>` ?




![07eDr7AY5I](https://user-images.githubusercontent.com/10191085/62023248-ff235c00-b19d-11e9-933b-ca387645fb71.gif)

Thanks!

**Comment by carlosrovira** [comment]
In Royale there's various binding beads. from this article:

https://royale.apache.org/binding-the-text-property-of-a-jewel-textinput-to-update-a-text-label/

"In this example, we use data binding at the application level, since the whole example is only a few lines of code. So we use the `ApplicationDataBinding` bead. This bead adheres to the Application strand, “composing” or “adding” the binding functionality at the application level. In a more complex application, you might decide you only need data binding in a particular View or Container. Then you could use a `ViewDataBinding` bead, or a `ContainerDataBinding` bead. PAYG ensures features like data binding are only present where you really need them, and not using up system resources by sitting around in parts of the application where they will never be used."

**Comment by angelhdz** [comment]
### Thanks for replying

I tried every combination I could think of and every order of MXML tags. ViewDataBinding, ContainerDataBinding, ApplicationDataBinding. None of it works.

```
<?xml version="1.0" encoding="utf-8"?>
<j:Application xmlns:fx="http://ns.adobe.com/mxml/2009"
        xmlns:j="library://ns.apache.org/royale/jewel"
              xmlns:js="library://ns.apache.org/royale/basic"
			   xmlns:html="library://ns.apache.org/royale/html"
			  xmlns:royale=".*" >
<j:beads>
		<js:ApplicationDataBinding/>
	</j:beads>

<fx:Script>
        <![CDATA[
                import org.apache.royale.jewel.Alert;
                import org.apache.royale.jewel.Button;
                import org.apache.royale.events.Event;
                

                private function onClick(e: Event ):void
                {
                    var target:Button = e.target as Button
                    Alert.show("Royale Test!" + target.text)
                   
                }

               
			
		]]>
			</fx:Script>

	
		
    <j:initialView>
	
		<j:View>
					
	<j:VGroup>
				<j:Button text="Default" id="button" click="onClick(event)"/>
				<j:Button text="Disabled">
					
				</j:Button>
				
				<j:Button text="Primary" emphasis="{Button.PRIMARY}"/>
				<j:Button text="Secondary" emphasis="{Button.SECONDARY}"/>
				<j:Button text="Emphasized" emphasis="{Button.EMPHASIZED}"/>
				<j:Button text="Disabled" emphasis="{Button.PRIMARY}">
					
				</j:Button>
</j:VGroup>


		</j:View>
    </j:initialView>

</j:Application>

```

The databinding with Jewel Themes only works when I add my components in a different MXML file.
If I add them in the main MXML file, no themes.

Of course, I could be doing something wrong because I'm not familiar with MXML or Royale.
But following all the examples I've read, I think I'm doing it correctly.

**Comment by carlosrovira** [comment]
Hi Angel,

just checked this example and you're right. Seems something is broken at Application level for binding. Hope others that has more expertise in that code could take a look and see what's broken. I think this is a regression. Thanks for reporting it.

**Comment by carlosrovira** [comment]
Hi,

this bug is about constant bindings. Normal binding works ok in Application, but if you bind a constant like the `Button.PRIMARY`, the binding does not work.

**Comment by angelhdz** [comment]
### Phew! 

I was starting to get crazy thinking I was doing something wrong!!!

Thank you for investigating this issue!

Yes, I noticed normal literal String bindings work. It's just with the Constants.

I think the issue is in the royale compiler where it reads the AS3 constants and processes the Jewel CSS classes and styles. 

I'll wait for a fix, but in the meantime, I will work with external modules to keep understanding Royale. I so want to start building my apps with this framework.

Thank you for your contributions and hard work for the community.

Cheers!
