### ISSUE TITLE
AdvancedDataGrid Doesn't get values from a function not even ManualData

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#398]
Hi 
@greg-dove Thanks for your Help
I have noticed that AdvancedDataGrid doesn't set values inside any function not even ManualData
if I do a declaration of data provider outside the function and initialize manualData inside a function it doesn't work

[Bindable] public var DataProviderIn:ArrayCollection;
private function getCityNames():void {		   
var DataProviderIn:ArrayCollection = new ArrayCollection([{ci_Name:"Attock Petroleum Limited", ci_Code:"0001"}]); 
}

But if I do Declaration and initialization outside the function it works

[Bindable] public var DataProviderOut:ArrayCollection = new ArrayCollection([{ci_Name:"Attock Petroleum Limited", ci_Code:"0001"}]); 

Example with Screenshot of index,html:
File: https://paste.apache.org/gpHP
![image](https://user-images.githubusercontent.com/42200979/53716748-b9c16380-3e77-11e9-9b1f-23beb49bbfa7.png)

In my Application, I am working with RemoteObject and set values of AdvancedDataGrid in ResultHandler but I can't do this because AdvancedDataGrid doesn't set even manual data inside a function so how it set the values of AdvancedDataGrid in a ResultHandler

**Comment by aharui** [comment]
Pashmina,  please create a simple test case with one button that sets manual data.  That should be roughly equivalent to what a resultHandler would do.  If it doesn't work, then attach the test case.

**Comment by greg-dove** [comment]
@pashminakazi Can you please advise, did the changes in amf_updates branch solve issue #397 ? For my suggestion about assigning issues to me, I should have explained that this was specifically for the amf/remoting support, because that is my current focus. I have not yet spent time looking at mxroyale components such as AdvancedDataGrid . (I may be able to look at other issues in time, but for now I am focusing on trying to make sure AMF encoding/decoding, which is used for the RemoteObject remoting services, is as compatible with flash as we can reasonably possible in terms of implementation)

**Comment by pashminakazi** [comment]
@greg-dove 
Thanks amf_update branch solve my issue
@aharui 
Thanks
