### ISSUE TITLE
Jewel UI :: Panel Component

### ISSUE THREAD

**Issue by safrizal** [apache/royale-asjs#409]
Please create this.

**Comment by carlosrovira** [comment]
Hi Safrizal,
currently there's a Jewel Card component that was thinked to be like Flex Panel, but is right that could have more work on it. Can you try it and let me know what do you think about it, and what you could need far beyond what is implemented?
thanks

**Comment by safrizal** [comment]
Apache Flex Alert Component extends from Panel, so, i will try to create Jewel Panel Component based on Jewel Alert

**Comment by carlosrovira** [comment]
Hi, if you want to make a Jewel Panel and submit as a PR for validation and inclusion in Royale you're welcome. You can start from Basic Panel component since most of the jewel components are based on Basic ones. Give it a try and let us know. For discussing, best to post in dev mailing list
thanks!
