### ISSUE TITLE
One Swc depended on another Swc Causes Index.html Blank

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#437]
I am compiling my own library DBIZLib.swc 
Console : https://paste.apache.org/h4c5d
what should i do to remove these warnings?
because if i ignore these warnings and compile any project index.html is blank
Errors:

Uncaught ReferenceError: applications_mx_managers_SystemManager is not defined at index.html:962

Uncaught Error: Bad dependency path or symbol: org.apache.royale.effects.IEffect
at visit (base.js:2796)
at visit (base.js:2808)
at visit (base.js:2808)
at goog.DebugLoader_.load_ (base.js:2815)
at Object.goog.require (base.js:846)
at index.html:957

https://user-images.githubusercontent.com/42200979/61864583-1ab30c00-aeeb-11e9-9a8f-690798fec1cd.png

**Comment by Harbs** [comment]
It looks like you're missing playerglobal.swc as an external dependency.

It would help to see what build configuration you are using.

**Comment by carlosrovira** [comment]
Recently Josh made changes to how libraries are linked. I'm not using ANT, but I think ANT solves this with config.xml files in projects. Basically instead of listing all in library-path node, you must use "external-library-path" node in libraries to ensure all the code in the libraries linked are not compiled into that library. Then in Application, you must continue using library-path, since you want all code used be compiled in the application. In this part your application maybe is missing playerglobal or js swcs as Harbs comment.
