### ISSUE TITLE
UiComponent.component being set to wrong value

### ISSUE THREAD

**Issue by yishayw** [apache/royale-asjs#440]

**Comment by yishayw** [comment]
Consider an application [1] with a custom mxml component [2].

I expect the radio buttons in [2] to have a component referencing the custom component, instead they reference the top level application.

The result is that selecting a radio button triggers a RTE.

[1] https://paste.apache.org/x5q2m
[2] https://paste.apache.org/paf3a

**Comment by yishayw** [comment]
@aharui , I don't see any place where UIComponent.component is set, other than in UIComponent.addingChild(). This seems to result in the default top level application being set. Any ideas, where else this should be set?

**Comment by aharui** [comment]
UIComponent.component is supposed to replace the Flex UIComponent.document.  "document" is a reserved word in JS so we gave it a new name (although maybe we should have named it "mxmlDocument".  You can make a Flex app and see how/where it sets UIComponent.document.  Royale should set UIComponent.component the same way.

However, if the compiler is responsible for generating code to set UIComponent.document, we may want to find a way to set it in AS code in Royale so the compiler doesn't have framework-dependent code generation.  In Royale, MXML-capable components have different APIs in their lifecycle so that could be a good place to set things.

**Comment by yishayw** [comment]
It looks like Flex is doing it in IMXMLObject.initialized(document:Object, id:String)

**Comment by aharui** [comment]
Taking a quick look, I think I would suggest renaming UIComponent.component to be UIComponent.mxmlDocument and have it return the _mxmlDocument in the base class (which will probably need to become protected).
