### ISSUE TITLE
Assigning ArrayCollection to ADG.dataProvider

### ISSUE THREAD

**Issue by alinakazi** [apache/royale-asjs#448]
We have few lines of code that were working in flex:
var arrDDResult:Array = e.result as Array;
arrDGDataProvider = arrDDResult[0][0] as ArrayCollection; 
Adg.dataProvider = arrDGDataProvider ;

Using Above lines in Royale arrDGDataProvider has null value

We have changed these lines into Royale like:
var arrDDResult:Array = e.result as Array;
arrDGDataProvider = arrDDResult[0] as ArrayCollection;
Adg.dataProvider  = arrDGDataProvider.getItemAt(0).source ;

After these changes ,Now its working as Flex But it takes more time to populate data in ADG .

It seems two Dimension Array  arrDDResult[0][0]  is not working in Royale.

**Comment by aharui** [comment]
I don't see a test case to analyze see why it would take more time.

In Flex/Flash, the runtime resolves types and knows how to interpret bracket access.  In Royale on JS, the browser runtime is not as smart and Royale's compiler must be told what the type is in order to generate anything other than simple property lookups via bracket access.

ArrayCollection is a Proxy so bracket access on Proxy must be explicitly typed.  So, in theory the following should work:

var arrDDResult:Array = e.result as Array;
arrDGDataProvider = (arrDDResult[0] as ArrayCollection)[0] as ArrayCollection;
Adg.dataProvider = arrDGDataProvider ;

Or:

var arrDDResult:Array = e.result as Array;
// assumes var arrDGDataProvider:ArrayCollection; 
arrDGDataProvider = arrDDResult[0] as ArrayCollection; 
Adg.dataProvider = arrDGDataProvider[0] ;

**Comment by greg-dove** [comment]
@aharui the only browser that does not support es6 Proxy is IE. Using that could allow it to work in the browser just like Flex/Flash... but obviously not for IE11. Something to consider in the not too distant future?
see: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy#Browser_compatibility

**Comment by pashminakazi** [comment]
https://paste.apache.org/t60p8

In our application we are retrieving data from Java side as
var arrDDResult:Array = e.result as Array;
arrDGDataProvider = arrDDResult[0] as ArrayCollection;
dg.dataProvider = arrDGDataProvider.getItemAt(0).source ;

In Example
var arrDDResult:Array = e.result as Array;          is replaced with

[Bindable] public var data:Array =  new Array(["abc", "f","abc", "f","abc"]);
var arrDDResult:Array = data as Array;

So,its not populating data in AdvancedDataGrid
please Replace e.result with suitable Data and then check this example

**Comment by pashminakazi** [comment]
data returned from server side is of type ArrayList<Hashtable[]>[]

and on retrieval we are assigning the result to dataprovider of adg:
  var arrDDResult:Array = e.result as Array;
               arrDGDataProvider = (arrDDResult[0] as ArrayCollection)[0] as ArrayCollection;
               dg.dataProvider = arrDGDataProvider ;

It takes too much time to populate the grid with data
during debugging we found that below given line takes 30 seconds to execute
  dg.dataProvider = arrDGDataProvider  

We have tried both of your provided solutions.

**Comment by pashminakazi** [comment]
Data Population Video:
![ezgif com-optimize (1)](https://user-images.githubusercontent.com/42200979/63691131-db4c4800-c827-11e9-995b-277aa6aa7eae.gif)

**Comment by alinakazi** [comment]
@aharui  Thanks a lot
