### ISSUE TITLE
module is not working .not prompt a module window

### ISSUE THREAD

**Issue by Dakshinads** [apache/royale-asjs#453]
Module file and Main file are also debug. but click the load module button not appeared module.

**Comment by carlosrovira** [comment]
You need to give us more info in order to help you. Maybe you're trying this example?
https://royale.apache.org/dividing-an-apache-royale-application-with-modules/
or is an example or your own?
How are you building? ANT? Maven?
Thanks

**Comment by Dakshinads** [comment]
This is MainJewelApp.mxml
<?xml version="1.0" encoding="UTF-8"?>

<j:Application xmlns:fx="http://ns.adobe.com/mxml/2009"
               xmlns:j="library://ns.apache.org/royale/jewel"
               xmlns:js="library://ns.apache.org/royale/basic"
               xmlns:html="library://ns.apache.org/royale/html">

    <fx:Script>
		<![CDATA[
            import org.apache.royale.jewel.ModuleLoader;   
          
            public function asc_loadModule():void
            {
                new_moduleLoader.loadModule();
            }
		]]>
	</fx:Script>
    
    <j:beads>
        <js:ApplicationDataBinding />
    </j:beads>

    <j:initialView>
        <j:View>
        
            <js:beads>
                <j:HorizontalCenteredLayout/>
            </js:beads>

            
        <j:Card id="dd">

                <html:H3 text="Dividing an Apache Royale application with modules"/>
                
                <j:Label html="This example uses Modules to load parts of the application"/>

                <j:ModuleLoader localId="new_moduleLoader"
                                modulePath="modules" moduleName="asc" />
                
                
                <j:Button text="Load a Module" emphasis="secondary" click="asc_loadModule()"/>
        </j:Card>
        </j:View>
    </j:initialView>
</j:Application>


this is asc.mxml(module)
<?xml version="1.0" encoding="utf-8"?>

<j:Module xmlns:fx="http://ns.adobe.com/mxml/2009"
        xmlns:j="library://ns.apache.org/royale/jewel"
        xmlns:js="library://ns.apache.org/royale/basic"
        initComplete="initModule()"
        >

   <fx:Script>
        <![CDATA[
            import org.apache.royale.utils.css.loadCSS;

          
            private function initModule():void
            {
              loadCSS('https://fonts.googleapis.com/icon?family=Material+Icons');       
            }
        ]]>
    </fx:Script> 

    <js:beads>
        <js:ContainerDataBinding/>
        <j:VerticalLayout/>
    </js:beads>

    
    <j:valuesImpl>
        <js:SimpleCSSValuesImpl/>
    </j:valuesImpl>

     <j:HGroup gap="3">
        <j:IconTextInput>
            <j:beads>
                <j:TextPrompt prompt="Search..."/>
                <j:SizeControl size="xlarge"/>
            </j:beads>
            <j:icon>

                <js:FontIcon text="{MaterialIconType.SEARCH}" material="true"/>
            </j:icon>
        </j:IconTextInput>
        <j:Button text="Search" emphasis="secondary">
            <j:beads>
                <j:SizeControl size="xlarge"/>
            </j:beads>
        </j:Button>
        
    </j:HGroup>

</j:Module>

I am using visual studio code and compile Royale sdk

**Comment by Dakshinads** [comment]
I do compiled module after then create a module folder, including to mainjewelapp debugging folder. copy the module debug files to module folder.

**Comment by Dakshinads** [comment]
[BE0013_Dividing_an_Apache_Royale_application_with_modules.zip](https://github.com/apache/royale-asjs/files/3532727/BE0013_Dividing_an_Apache_Royale_application_with_modules.zip)

These are all files. Please check the file and help.
Thank You

**Comment by Dakshinads** [comment]
This is the folder
please check the include file and code. Help me my wrong codings.
I will hope reply soon
Thank you

**Comment by carlosrovira** [comment]
Hi, I think the problem is in building since Apps with modules implies build two projects (the app and the module). In Royale we use to prepare builds for Maven and ANT build systems. In this case I only created and tested the Maven one. I tried to create an ANT file too but I'm not sure its working. others with more ANT knowledge should try it. For IDEs the same. VSCode and Moonshine probably will enhance eventually the module workflow to make it more easy.

The maven pom.xml file is the one that makes the magic and after compile the module copy it to the main app target folder to make it available.

So to make this work in VSCode (or from command line) you must use Maven build. So please try this:

(Note that you need to have maven installed and ready to work and use latest knightly SDK)

1.- In VSCode preset CMD+SHIFT+B and select "Build with Maven"

That's all. Then you get the app build  in this path `/royale-asjs/examples/blog/BE0013_Dividing_an_Apache_Royale_application_with_modules/MainJewelApp/target/javascript/bin`. here you'll get js-release and js-debug folders.

Let me know if that work for you.

Thanks

**Comment by Dakshinads** [comment]
Please give me your example file with debug files(Full folder). I think Help debug file for me.
Thank you
