### ISSUE TITLE
Any clues as to equivalent for this

### ISSUE THREAD

**Issue by wrath2019** [apache/royale-asjs#459]
Calling programs through wsdl in flex mxml but need to use apache royale equivalent but not seeing anything with all these options.  Any ideas?
<js:WebService id="SessionEngine"
	fault="faultHandler(event)"
	result="resultHandler(event)" 
	invoke="invokeHandler(event)" 
	load="headers()" 
	wsdl="StockSrv.wsdl" useProxy="false">  
	<js:operation name="ACTION_LOGIN"/> 
	<js:operation name="ACTION_VALDATE_INQ"/>
	<js:operation name="ACTION_VALDATE_UPD"/>
	<js:operation name="ACTION_ENTER_INVENT"/>
		
</js:WebService>

	import mx.rpc.soap.SOAPHeader;

**Comment by carlosrovira** [comment]
Hi,

don't remember flex `WebService` was migrated. Maybe I'm wrong and others could say more. `HTTPService`and `RemoteObject(AMF)` came due to people interested in migrate that code. Maybe you're the first one for WS. Hopefully WS should be more easy to migrate since is more standard. You could evaluate start this effort and contribute to Royale.

**Comment by wrath2019** [comment]
I would do that but my problem is I had very limited exposure to flex a long time back so I am trying to keep my head above water but if you could give me some guidance on how to start I could give it a shot if no one has actually completed this type of task I will need to.

**Comment by carlosrovira** [comment]
Hi, that would be great :). I think others in the team could guide you better than I. I only used flex WS a couple of times when I was learning flex around 2003-2005, so it's not something I control. So hope others assist you in this task.

My advice for now is that you search for javascript solutions for consuming web services. Once you have located some JS way to do that, you can figure how to wrap it in Royale and use it from your App. Then a next step could be try to model your solution as close as possible as flex one in terms of class names, properties, so you can migrate your code. HTH at least for now :)

**Comment by aharui** [comment]
AFAIK, we have not tried to emulate WebService in Royale.  Things like this only get done when somebody asks for it.  I wasn't sure if people were replacing their SOAP/WSDL backends with something else.

I've got one other thing I'm working on, then I'll see what it takes to get it working.  The Flex SOAP code seems to use flash.xml.XMLDocument so that will be the big thing to replace/emulate.

**Comment by wrath2019** [comment]
Thank you

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by aharui** [comment]
I think this is working, except for XMLDocument.
