### ISSUE TITLE
XML declaration warning

### ISSUE THREAD

**Issue by nihavend** [apache/royale-asjs#470]
While declaring xml in mxml, I am getting warning from the compiler for case 1, and fixed with case 2. 

case1 : 
```actionscript
private function refreshSelect(data:XML):void  {
    var xml:XML = <mydata id="" />
    xml.@id = data;
    jobTree.refreshTree(xml);
}
```
converted to : 
```javascript
com.likya.pinara.main.PinaraUI.prototype.com_likya_pinara_main_PinaraUI_refreshSelect = function(data) {
  var /** @type {XML} */ xml = new XML( '<mydata id="" />\r\
\t\t\t\t');
  xml.setAttribute('id', data);
  this.jobTree.refreshTree(xml);
};
```
warning :
```shell
Sep 16, 2019 6:09:36 PM com.google.javascript.jscomp.LoggerErrorManager println
WARNING: D:/dev/royale-emulation-works/github/bin/js-debug/com/likya/pinara/main/PinaraUI.js:367: WARNING - String continuations are not recommended. See https://google.github.io/styleguide/jsguide.html#features-strings-no-line-continuations
  var /** @type {XML} */ xml = new XML( '<mydata id="" />\r\
                                        ^
```
case2 : 
```actionscript
private function refreshSelect(data:XML):void {
    var xml:XML = <mydata id="" />;
    xml.@id = data;
    jobTree.refreshTree(xml);
 }
```
converted to : 
```javascript
com.likya.pinara.main.PinaraUI.prototype.com_likya_pinara_main_PinaraUI_refreshSelect = function(data) {
  var /** @type {XML} */ xml = new XML( '<mydata id="" />');
  xml.setAttribute('id', data);
  this.jobTree.refreshTree(xml);
};
```
No warning.

**Comment by greg-dove** [comment]
Thanks for reporting this. I am just adding comments here for extra info. I may get to this issue later this week, or some else might get to it first. The warning you see is a Google Closure Warning for the generated js output which is the XML literal content expressed as a multiline string. I have checked this recently because the warning output is a common problem with XML and there appears to be no way to suppress the warning in GCC (as there are with other warnings that GCC generates, which we can suppress). In terms of the multiline string vs. the single line string passed to XML constructor, that seems to be related to parsing and the presence or absence of a semicolon as a terminator for the XML literal. The compiler does not know about the XML.ignoreWhiteSpace setting or not, so perhaps it might be correct as it is. But I can check what string content avmplus uses in this specific example and make sure we match that. The warning side of things is another general matter. Unless there is a way to switch that off, the only way to avoid it will be to output the string content in a way that does not cause GCC to dislike it.
