### ISSUE TITLE
How to create Tree, Menu using jewel? can or can't?

### ISSUE THREAD

**Issue by Dakshinads** [apache/royale-asjs#471]

**Comment by greg-dove** [comment]
I have a simple collapsible NavigationItemRenderer class which I have in my local version of Jewel. It is not really a Tree, so it's not using Hierarchical data, but does support a two level navigation structure. I'm not sure what exactly you're needing but it might work depending on what you want. I checked in with Carlos on that, and he's happy for me to add that, so I'll add it later this week. Whether or not it stays in its current form though I cannot say.

**Comment by Dakshinads** [comment]
thanks

**Comment by Dakshinads** [comment]
When will you give advanced grid?

**Comment by carlosrovira** [comment]
Hi,

I'm right now focused on complete documentation (both content and improve layout), since is what people asked to do. In this way the actual set of Jewel will be well documented and revised.
I'd want to work on Tree, Menu, DataGrid and other components for Jewel but must say that don't know when I could do that since it will be done for fun not for a necessity of any project. Others are free to work on it and contribute to the project or consider to contact me (or others) to work on them as [comercial support](https://royale.apache.org/royale-commercial-support/), so it could come sooner than later.

**Comment by carlosrovira** [comment]
Hi @Dakshinads 

@greg-dove added `CollapsibleNavigationSectionRenderer` to repository, also and example in TourDeJewel.  You can get all of this in the latest commits 

Hope it's useful to you :)

![collapible-renderer-transition](https://user-images.githubusercontent.com/1701640/65392598-dd49ee00-dd76-11e9-92c2-96948764b624.gif)

**Comment by Dakshinads** [comment]
Of course I thank you. But I saw how to take this sub menu of tour De jewel. Give me the source code if you can.
Thank You @carlosrovira

**Comment by carlosrovira** [comment]
Hi @Dakshinads, several files are involved here. With latest nightly build or by building latest source code in repo. You must take into account the following files from Tour De Jewel example:

- This is the [renderer](https://github.com/apache/royale-asjs/blob/develop/examples/royale/TourDeJewel/src/main/royale/itemRenderers/NavigationGroupExampleItemRenderer.mxml) to use with Navigation component. This renderer is extended from `CollapsibleNavigationSectionRenderer`
- Navigation is used in [MainContent](https://github.com/apache/royale-asjs/blob/develop/examples/royale/TourDeJewel/src/main/royale/MainContent.mxml)
- ItemRenderer is assigned via [css](https://github.com/apache/royale-asjs/blob/develop/examples/royale/TourDeJewel/src/main/resources/jewel-example-styles.css)
- Model for the Navigator is [here](https://github.com/apache/royale-asjs/blob/develop/examples/royale/TourDeJewel/src/main/royale/models/MainNavigationModel.as).
- VO used in Navigator is [here](https://github.com/apache/royale-asjs/blob/develop/examples/royale/TourDeJewel/src/main/royale/vos/NavigationLinkVO.as).

Take into account that I just updated all jewel themes (if you're using specific one that comes with Royale instead of main `JewelTheme` master theme).

**Comment by Dakshinads** [comment]
But I have some errors. 

1 Error: This tag could not be resolved to an ActionScript class. It will be ignored.

<j:CollapsibleNavigationSectionRenderer xmlns:fx="http://ns.adobe.com/mxml/2009"
^

19.273689 seconds
The terminal process terminated with exit code: 3

I think missing a CollapsibleNavigationSectionRenderer. 
Thank you

**Comment by carlosrovira** [comment]
Hi, take into account that this is a new class recently added, so you must download a nightly build or build from source.

**Comment by Dakshinads** [comment]
I am latest source code is downloaded. Then compiled, but only displayed, this error.

**Comment by carlosrovira** [comment]
You can see it working in Tour De Jewel. Try to compile TDJ in local. That should work for you. From that you can see what could be the problem, maybe you are missing something in you code or something is not properly configured.

**Comment by Dakshinads** [comment]
Please give me latest SDK for download.
Thank you.
