### ISSUE TITLE
On sdk 0.9.6 build 20191006 (today) no way to use MX library

### ISSUE THREAD

**Issue by cristallium** [apache/royale-asjs#495]
Hi,

I just download the last **0.9.6 build 20191006** to replace my old 0.9.6 (from about 1 week old)

```
<royale-sdk-description>
<name>Apache Royale</name>
<version>0.9.6</version>
<build>20191006</build>
```

With this build no way to use Mx library , it seem to be unknow. 

Here is my code :

```
<mx:Application xmlns:fx="http://ns.adobe.com/mxml/2009"
			   xmlns:j="library://ns.apache.org/royale/jewel"
			   xmlns:js="library://ns.apache.org/royale/basic" 
               xmlns:mx="library://ns.apache.org/royale/mx"
               xmlns:local="*" initialize="ev_creationComplete()">
```

On editor (vscode) `mx:Application` is red hightlighted and tooltip show 

**"This tag can not be resolved in ActionScript class. It will be ignored. (1450)"**

If I switch to 0.9.4 (official release) then it working.

When run compiler this error is shown:  _"Error: This tag is unexpected. She will be ignored."_

Regards

**Comment by aharui** [comment]
I think in 0.9.6 you will need to add to the compiler options:

```+configname=flex```

**Comment by cristallium** [comment]
I tried  adding this in asconfig.json 
`"js-compiler-option": ["+configname=flex"] `
But same issue :(
Why it would be a compiler option ? If I set 0.9.4 sdk without changing anything it is working, so it must be a wrong file in 0.9.6 sdk folder ?

**Comment by Harbs** [comment]
It's not a js-compiler option. If you look at the compiler output, you should see `+configname` (probably right below `+royalelib`). You probably have `+configname=royale` instead of `+configname=flex`.

When compiling a Royale application, you need to to specify what "type" of application you're compiling. The specified config effects the default SWCs loaded. I believe the current list of configs are: `js`, `node`, `royale`, `flex`, `air`, and `airmobile`.

If none of the default configs fit your use case, you can also specify the necessary SWCs explicitly.

**Comment by cristallium** [comment]
Many thanks, as I'm using  ActionScript & MXML language extension for vscode, I found that I must add the following line to asconfig.json
`"config": "flex"` 
I don't understand why I don't need it when selecting 0.9.4 sdk

**Comment by Harbs** [comment]
That's correct. I didn't know if you were using that.

We used to include all the SWCs, but we found that it sometimes caused conflicts. (It also pollutes the options for code completion.) So we now only include the MX and Spark swcs if you specify `flex`.

**Comment by carlosrovira** [comment]
To complement: 

If you want to use `"config": "royale"` (instead of flex) and at the same time **MXRoyale** you can add that swc so **VSCode** can recognize it.

```
"library-path": [
       "${royalelib}/js/libs/MXRoyaleJS.swc"
 ],
 "js-library-path": [
       "${royalelib}/js/libs/MXRoyaleJS.swc"
 ]
```

Additionally: You would be interested in use **MXRoyale** for non visual things like `HTTPService` or `RemoteObject`, and css from **MXRoyale** could be not desired. In that case you can exclude that CSS to avoid CSS conflicts between MX/Spark and other ui set, specially Jewel in this way:

`-compiler.exclude-defaults-css-files=MXRoyale-${royale.framework.version}-js.swc:defaults.css`

**Comment by cristallium** [comment]
This is a **VERY VERY usefull complement** !!! Many thanks

**Comment by cristallium** [comment]
For vscode users here is what to add in as3config.json: 
	
```
"additionalOptions": 
		"-compiler.exclude-defaults-css-files=MXRoyaleJS.swc:defaults.css",
```

**Comment by piotrzarzycki21** [comment]
Does intellisense working for you? In Moonshine with Royale MX project doesn't work.

**Comment by cristallium** [comment]
with configuration=royale only if I add this 
```
 "js-library-path": [
			"${royalelib}/js/libs/MXRoyaleJS.swc"
		],
```

Here is my as3config.json working

```
{

	"config": "royale",
	"compilerOptions": {
		"targets": [
			"JSRoyale"
        ],
        "theme": "${royalelib}/themes/JewelTheme/src/main/resources/defaults.css",
        "source-map": true,
        "source-path": [
            "src"
		],
		"library-path": [
			"${royalelib}/js/libs/MXRoyaleJS.swc"
		],
		  "js-library-path": [
			"${royalelib}/js/libs/MXRoyaleJS.swc"
		]
		
		
	},
	"additionalOptions": 
		"-compiler.exclude-defaults-css-files=MXRoyaleJS.swc:defaults.css",
	"files":
	[
		"src/Main.mxml"
	]
	
}
```
note that `"library-path": [	"${royalelib}/js/libs/MXRoyaleJS.swc"	],` seems useless

**Comment by carlosrovira** [comment]
Yes, I think the other one is useless for now, since the first one is targeting JS directly.
The other could be for SWF (or both) and should target the appropriate SWC, but again, since Jewel is really JS (although is prepared to be SWF some day if we work on it) is of no use for now.

One effort I started some months ago is separate things in MXRoyale in libs, but I couldn't. Hope some day we can do that separation and this kind of combinations could be more easy. Maybe someone with more time can work on that separation, I think it will be very useful to avoid changes in user projects at a later time.

**Comment by aharui** [comment]
The SDK contains support for several likely configurations.  One is migrating Flex apps to the MXRoyale/SparkRoyale libraries.  Folks are expected to use +configname=flex and thus load flex-config.xml instead of royale-config.xml.  Royale-config.xml is a configuration to support development without the MXRoyale/SparkRoyale libraries.  Some folks do need to mix in MXRoyale into a royale-config.xml setup, but many won't.  

The compiler supports library-path, js-library-path, and swf-library-path options.  If you or any other -config.xml file uses -js-library-path then -library-path is ignored for a JS compile and similar for -swf-library-path.

**Comment by carlosrovira** [comment]
Hi Alex, I must say that right now the cases of pure migration (flex config) and mixed (royale config with MXRoyale just for AMF or HTTP communication uses) are equally used and needed. I think the effort I started to do months ago about break MXRoyale into pieces is very needed. Another thing we could do is to create a "Jewel config" that uses jewel + MXRoyale", but again, I think that doesn't  remove the need to break the monolithic MXRoyale lib
