### ISSUE TITLE
Issue in mx:MXAdvancedDataGridItemRenderer

### ISSUE THREAD

**Issue by alinakazi** [apache/royale-asjs#501]
Test case : https://paste.apache.org/vniyg

data. is not working and mx:MXAdvancedDataGridItemRenderer is not working. compile time errors and functionality issues in some other cases

**Comment by alinakazi** [comment]
we have tried by changing   mx:MXAdvancedDataGridItemRenderer   to s:MXAdvancedDataGridItemRenderer data. is working but its not fully functional as it shows blank output on screen. The output .js file has compilation error e.g :  }this...  semi column expected error etc

**Comment by pashminakazi** [comment]
Mxml File : https://paste.apache.org/q1y6z
.Js File : https://paste.apache.org/xydlf
Output : 
![image](https://user-images.githubusercontent.com/42200979/66821404-ceacbc00-ef5b-11e9-9709-83581ead6de5.png)
![image](https://user-images.githubusercontent.com/42200979/66821693-4549b980-ef5c-11e9-9757-641914ad4ee4.png)
![image](https://user-images.githubusercontent.com/42200979/66821698-4aa70400-ef5c-11e9-9858-23d15520689f.png)
![image](https://user-images.githubusercontent.com/42200979/66821709-4ed32180-ef5c-11e9-9a5a-8f2abf5e4644.png)


In Example or in our application's file when we are using this 
<mx:AdvancedDataGridColumn>
	<mx:itemEditor>
		<fx:Component>
			<mx:VBox>

and

<mx:AdvancedDataGridColumn>
		<mx:itemEditor>
			 <fx:Component>
			     <s:MXAdvancedDataGridItemRenderer>

Output is blank because .js file has Error : 
![image](https://user-images.githubusercontent.com/42200979/66822085-f81a1780-ef5c-11e9-96da-c02cf42fd808.png)

**Comment by yishayw** [comment]
This issue is a bit confusing. MXAdvancedDataGridItemRenderer probably shouldn't exist. Use mx:AdvancedDataGridItemRenderer instead. Also, grid columns should be wrapped in a <columns> tag. I only now saw your comment from 10 hours ago which does more or less that. I'll try to debug that tomorrow.

**Comment by pashminakazi** [comment]
MXAdvancedDataGridItemRenderer is present in both Projects MXRoyale and SparkRoyale but added only in MXRoyale Classes.So i added it in SparkRoyale Classes
Because if i use mx:MXAdvancedDataGridItemRenderer then it gives the compilation Error on "data."
That's why i am using s:MXAdvancedDataGridItemRenderer as we were using  s:MXAdvancedDataGridItemRenderer in Flex

**Comment by yishayw** [comment]
While checking out the mx example I stumbled upon various runtime errors. Particularly, it looks like you can't add event handler code in AdvancedDataGridItemRenderer in-line components.

**Comment by yishayw** [comment]
@alinakazi , my advice is to simply use mx:AdvancedDataGridItemRenderer. It works for me, barring issue #514, it works for me.

**Comment by yishayw** [comment]
> @alinakazi , my advice is to simply use mx:AdvancedDataGridItemRenderer. Barring issue #514, it works for me.

This is how I would do it:

Application
https://paste.apache.org/s6qvn

Renderer1.mxml
https://paste.apache.org/quhdu

Renderer2.mxml
https://paste.apache.org/6o3fo

**Comment by aharui** [comment]
Probably best to fix the compiler or framework code instead of making everyone refactor.  The whole point of the emulation component set is to provide a working emulation, and to try not to force refactoring.

**Comment by aharui** [comment]
Go back to using mx:MXAdvancedDataGridItemRenderer with the fix for #514.  If you still have problems, open a new issue.

**Comment by yishayw** [comment]
> Probably best to fix the compiler or framework code instead of making everyone refactor.  The whole point of the emulation component set is to provide a working emulation, and to try not to force refactoring.

Sounds good, thanks.
