### ISSUE TITLE
Issue in dbzutil 

### ISSUE THREAD

**Issue by alinakazi** [apache/royale-asjs#507]
File is compiled successfully but has run time issues
file:
https://paste.apache.org/6diqe

Test case is available on VDI.

**Comment by alinakazi** [comment]
Project Details are :
https://paste.apache.org/cpo8y

**Comment by pashminakazi** [comment]
![image](https://user-images.githubusercontent.com/42200979/66917624-2a984300-f037-11e9-8e0b-d0d05b2f4d6e.png)

**Comment by alinakazi** [comment]
@aharui  Please check this issue on our VDI. Thanks in Advance

**Comment by aharui** [comment]
The important part of your code is here

```
		//Get Selected Row index of AdvancedDataGrid
		public static function getSelRowIndex(dg:AdvancedDataGrid, aFieldName:String, aSelKey:String):uint {
			var rowIndex:uint = 0;
			if(aSelKey != null) {
				var breakMainLoop:Boolean = false;
				var dgDP:Object = dg.dataProvider;
				var arrDGSelKey:Array = aFieldName.split("~");
				var arrVOSelKey:Array = aSelKey.split("~");
				var strDGSelKey:String = "";
				var strVOSelKey:String = "";
				for (var i:int = 0; i < arrVOSelKey.length; i++) {
					strVOSelKey += arrVOSelKey[i] + "~";
				}
				strVOSelKey = strVOSelKey.indexOf('~') > -1 ? strVOSelKey.substring(0, (strVOSelKey.length)-1) : 
					strVOSelKey;
				if(dgDP != null) { 
					for (var j:int = 0; j < dgDP.length; j++) {
						for (var k:int = 0; k < arrDGSelKey.length; k++) {
							strDGSelKey += dgDP[j][arrDGSelKey[k]] + "~";
						}
```

Because dgDP is declared as an Object,

`var dgDP:Object = dg.dataProvider;`

the compiler does not know it is an ArrayCollection requiring Proxy access.  In Flash it didn't matter, the Flash runtime would detect that the code is reading from a Proxy like ArrayCollection, but in the browser (without Flash) it does matter.  The JavaScript runtime does not know what a Royale Proxy is (at least, not now).

So, if you get errors working with a Proxy like ArrayCollection, make sure the compiler knows you are working with an ArrayCollection.  Otherwise array access like `dgDP[j]`;

IMO, the code to use should look more like:

`var dgDP:ArrayCollection = dg.dataProvider as ArrayCollection;`

**Comment by alinakazi** [comment]
Thanks we have changed 
var dgDP:Object = dg.dataProvider;
 to 
var dgDP:ArrayCollection = dg.dataProvider as ArrayCollection;
and the issue has been resolved.
