### ISSUE TITLE
About As2 and As2/3 components

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [apache/royale-asjs#51]
Hi,
is Royal compatible with as2 and as2/3 mx components?

thanks

**Comment by piotrzarzycki21** [comment]
Hi @ROBERT-MCDOWELL ,

Apache Royale is a framework where you are using ActionScript 3 and MXML when you are developing your applications. Existing components are very different than those which you get used to in Flex. Encourage you to ask any specific questions on the Apache Royale users list -> http://royale.apache.org/

Piotr

**Comment by ROBERT-MCDOWELL** [comment]
Ok thanks Piotr

**Comment by aharui** [comment]
FWIW, the reason Royale components are not directly compatible with Flex is because Royale components are designed to be as optimal as possible for running in a browser so some things had to change.  It is probably possible to create a component set that is more backward compatible with Flex but it will be bigger and slower.
