### ISSUE TITLE
2d Array not working with Royale

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#532]
In Flex we are using 2d Array like
var arrDDResult:Array = e.result as Array;
arrDGDataProvider = **arrDDResult[0][0]** as ArrayCollection;
dg.dataProvider = arrDGDataProvider as ArrayCollection;

This is not working in Royale so we replace it with

var arrDDResult:Array = e.result as Array;
arrDGDataProvider = **arrDDResult[0]** as ArrayCollection;
dg.dataProvider = arrDGDataProvider.getItemAt(0).source;

But in some Cases **getItemAt** is throwing Error :
![image](https://user-images.githubusercontent.com/42200979/67670229-44217f00-f995-11e9-8f20-b238d98dc952.png)

**Comment by pashminakazi** [comment]
In this File this.length is 0 but in other Files there are some data so how can we use 
var arrDDResult:Array = e.result as Array;
arrDGDataProvider = arrDDResult[0][0] as ArrayCollection;
dg.dataProvider = arrDGDataProvider as ArrayCollection;
In Royale

Example File : https://paste.apache.org/jzha7
Java Side Functions : https://paste.apache.org/nymdm

**Comment by aharui** [comment]
If you can log into the VDI and get the debugger to stop at the screen with the exception, I can try logging in and investigating further.

**Comment by pashminakazi** [comment]
ok give me 10 mints i will do it

**Comment by aharui** [comment]
No rush.  I have to stop for tonight.  I will look when I start my day tomorrow for me.

**Comment by pashminakazi** [comment]
Latest SDK is updated on VDI 
Company Setup with PickList_SImple
![PickList](https://user-images.githubusercontent.com/42200979/67744084-5b6a7600-fa42-11e9-8000-7db4527c1026.gif)

**Comment by aharui** [comment]
e.result is an Array with one item that is an ArrayCollection.  So `arrDDResult[0]' is an ArrayCollection which is a subclass of Proxy.  In Flash, the runtime can determine the type of the object and use the appropriate access.  In JS it cannot, so when migrating, Royale code that accesses Proxy (and XML) needs strong-typing to tell the compiler what the appropriate access is.

That's why `arrDDResult[0][0]` does not work in Royale, because this is not a 2d array.  The second `[0]` is accessing an ArrayCollection, not an Array.

You should be able to use:

`(arrDDResult[0] as ArrayCollection)[0]`

getItemAt is not being used in this scenario so I cannot investigate any errors as described earlier in this issue.

Choose the correct code for accessing the ArrayCollections and then see if there are other issues.
