### ISSUE TITLE
Cannot Access Module as Variable in another Module

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#538]
On VDI Uncomment 
<compile-mxml folder="/com/dbz/modules/SAL/" relmap="../../../../" example="dbzLubricantFreight"/>

In dbzLubricantFreight we are using Module "dbzMaterialIssue" like
import com.dbz.modules.INV.dbzMaterialIssue;
Bindable] private var frmMIN:dbzMaterialIssue;

Type was not found or was not a compile-time constant: frmMIN:dbzMaterialIssue
Console Error :
![Module](https://user-images.githubusercontent.com/42200979/67747435-848f0480-fa4a-11e9-92ad-497e65b6d2bc.png)

**Comment by aharui** [comment]
As explained in #529, a module's class should not be directly referenced in the main application or another module, as compiling and linking would require linking in the module instead of loading it later.

In Flex, this might work if you have your source-paths set to include the module, but then your modules weren't really modules.

In Royale, you could still use more source-paths, but it is probably better to use modules properly.
