### ISSUE TITLE
Issue in MaskedDateField extends DateField

### ISSUE THREAD

**Issue by alinakazi** [apache/royale-asjs#559]
Go to **Inventory** from Setup in Menu 
Go to **Setups** 
Carriage/Freight - > contractor

file : dbzCarriageContractorSetup at path D:\DBIZSOL\Main\Royale\src\com\dbz\modules\INV
file : MaskedDateField at path  D:\DBIZLib\src\com\dbz\controls
![image](https://user-images.githubusercontent.com/36731338/68923070-3eb48a80-0732-11ea-8b22-cb272ff5406b.png)

**Comment by aharui** [comment]
Did the Flex app also get a Fault event in this Setup?  It looks to me that the Fault Handler (fn_HandleFault) is not written correctly.  I don't think the Fault Handler can expect that currentTarget is set as the Fault Handler is called from the AsyncToken responders and not called via dispatchEvent (until later).

The Fault being sent to the Fault Handler is:
"Detected duplicate HTTP-based FlexSessions, generally due to the remote host disabling session cookies.  Session cookies must be enabled to manage the client connection correctly"

So if the Flex application did not get a Fault, but the Royale application is, then you will have to resolve why that is as well as fix up the code in fn_faultHandler

**Comment by alinakazi** [comment]
![dbzcarriagecontractorsetup](https://user-images.githubusercontent.com/36731338/69135408-eb15aa00-0a6d-11ea-85b0-6074d753c11a.png)

![image](https://user-images.githubusercontent.com/36731338/69135596-34fe9000-0a6e-11ea-890a-2a2eb0a5ee61.png)

![image](https://user-images.githubusercontent.com/36731338/69135626-45af0600-0a6e-11ea-8623-b534755c4b91.png)

**Comment by alinakazi** [comment]
@aharui  

Issue is because of maskedDateField and maskedTextInput . see the above given screenshots

**Comment by aharui** [comment]
I made some changes and now there is some new error

**Comment by aharui** [comment]
OK, the Contractor setup appears without throwing uncaught exceptions.
