### ISSUE TITLE
Uncaught TypeError: Cannot read property 'setSelection' of null

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#583]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.

Go to RI from Select in Menu
Go to Action Plan Execution from Setups in Menu
File : com/dbz/modules/RI/dbzActionPlanExecutionCriteria.mxml

In spark RadioButton : 
![image](https://user-images.githubusercontent.com/42200979/69422637-f571c580-0d45-11ea-8b2a-898ee31b39dd.png)
Uncaught TypeError: Cannot read property 'setSelection' of null
at spark.components.RadioButton.set__selected (RadioButton.js:149)

**Comment by aharui** [comment]
It looks like you made a commit to fix this.  Can it be closed?

**Comment by pashminakazi** [comment]
No, it's not working

**Comment by aharui** [comment]
I don't see "RI" in select menu

**Comment by pashminakazi** [comment]
RI means Retail Inspection

**Comment by aharui** [comment]
I'm not seeing that either.  Note that the VDI still wants to load things with "shm" instead of "dbz" and I have to spend time altering that in the debugger.

**Comment by alinakazi** [comment]
In flex we have file names starting with 'shm........' and while porting our application to royale we have renamed all files,now all files are starting with 'dbz.......'.
there may be extra files available in D:\DBIZSOL\Main\Java\web starting with 'shm....'. 
But these files are useless. Because if you will search shm in our source you will not find any file name starting with shm.  

@aharui 
If you see any file on vdi loading shm instead of dbz please tell me file name i will see

**Comment by aharui** [comment]
On the VDI, loading Inventory or Purchase module tries to load from com/shm and use "shmInventoryModule" and "shmPurchaseModule".  And loading Carriage/Contractor setup loads from com/shm and uses "shmCarriageContractorSetup"

**Comment by alinakazi** [comment]
It should load from com/dbz and should use dbzCarriageContractorSetup

**Comment by alinakazi** [comment]
I can look into it. When you finish your work day today. Do mail me, I will connect the VDI. I think the source should not contain any com/shm also shouldn't contain any file starts with shm
