### ISSUE TITLE
AdvancedDataGrid focus issue (selectedIndex should be last selectedIndex after saving)

### ISSUE THREAD

**Issue by alinakazi** [apache/royale-asjs#584]
![28](https://user-images.githubusercontent.com/36731338/69499618-c6279980-0ea8-11ea-9113-ac503f836a70.gif)

When user select second last record and press save button the detail of entry get disappear.

**Comment by alinakazi** [comment]
![29](https://user-images.githubusercontent.com/36731338/69499634-ef482a00-0ea8-11ea-810b-04e20f80377e.gif)
System behave incorrectly on resaving. System should remain on the selected entry which has been resaved.

**Comment by alinakazi** [comment]
Go to Purchase Module 
Setups - > Shipment Modes

file name dbzShipmentModeSetup

**Comment by aharui** [comment]
The dataProvider is being changed which causes the renderers to be refreshed.  I was trying to debug into the code to see what caused the dataProvider to be changed, but then someone logged into the VDI and kicked me out, so I'm going to stop doing any VDI work since it is near the end of my work day anyway.

Ideally, the dataProvider would not be changed.  I can see that it contains the same data, but I think it is a new instance.  But also, the DataGrid code doesn't currently check to see if any of the renderers are selected.  If it did, you probably wouldn't notice.  So if there is a good reason to change the dataProvider, then I recommend changing AdvancedDataGridItemRenderer to check the selectedIndex before choosing a background color.

**Comment by alinakazi** [comment]
Pashmina has logged into vdi for 5 mins. We will take care next time.we will not access the vdi again. I think on reassigning new values to  the dataprovider advancedDataGrid isn't updating the grid values.

**Comment by aharui** [comment]
When saving, there is a new server request.  It probably gets the updated data from the server and resets the data provider.  That seems reasonable, so I will update AdvancedDataGridItemRenderer to check for selectedIndex

**Comment by alinakazi** [comment]
@aharui Thanks for the fix
