### ISSUE TITLE
Typed code is not visible in TextInput 

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#613]
TextInput field is editable and if we create something in Code field it doesn't appear on time of typing.

Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Fixed Assets from Select in Menu
Go to Cost Centre from Setups in Menu
File : com/dbz/modules/Common/dbzCostCenterSetup.mxml
Flex vs royale video

![Cost center setup code flex-royale](https://user-images.githubusercontent.com/42200979/70502386-6be23600-1b42-11ea-9a72-48c339a91900.gif)

Go to Fixed Assets from Select in Menu
Go to Authorized Person from Setups in Menu
File : com/dbz/modules/FA/dbzAuthorizedPerson.mxml
![Authorized person code](https://user-images.githubusercontent.com/42200979/70502387-6be23600-1b42-11ea-90f2-2e87314dbe41.gif)

Go to Purchase from Select in Menu
Go to Shifts from Setups in Menu
File : com/dbz/modules/Common/dbzShiftSetup.mxml
Flex vs royale video

![shift setup code flex-royale](https://user-images.githubusercontent.com/42200979/70502393-6e449000-1b42-11ea-9113-1848c4097bf5.gif)

**Comment by aharui** [comment]
I can investigate when I start my day tomorrow.  If these are all your custom MaskedTextInput and a regular TextInput is working, one experiment you can try during your workday is to override invalidateDisplayList in MaskedTextInput and have it call updateDisplayList(width, height).  You might need to add a flag to stop infinite loops.

**Comment by pashminakazi** [comment]
after adding this in MaskedTextInput
override public function invalidateDisplayList():void
{
	if (parent != null) {
		 updateDisplayList(0,0);
	}
	else {
		updateDisplayList(width, height);
	}
	invalidateDisplayListFlag = true;
}
Setup :
![image](https://user-images.githubusercontent.com/42200979/70514899-3e9f8300-1b56-11ea-9328-93d96e294e8c.png)
I am reverting my changes of invalidateDisplayList in MaskedTextInput.
Investigate this issue when you start your day tomorrow.
Thanks

**Comment by aharui** [comment]
In the debugger, I replaced the invalidateDisplayList() call at the end of MaskedTextInput.handleInput with updateDisplayList(width, height) and simple text entry seemed to work.  You may also need to replace the invalidateDisplayList at the end of MaskedTextInput.interceptKey.  

I don't know what the expected behavior is for more complex editing scenarios.  I cannot really tell what is expected by watching these videos.  You may have to post a sequence of still images with words describing expected and actual behavior.

**Comment by aharui** [comment]
I don't think your attempt to override invalidateDisplayList was correct, but it is probably better to selectively replace invalidateDisplayList calls with updateDisplayList.  I'm concerned that having invalidateDisplayList call updateDisplayList could cause performance issues or visual update issues.  Because some browser updates are immediate, it isn't clear that Royale components can rely on invalidation to do updates without visual issues, so it may be that custom components that rely on invalidation will have to be modified as needed.

**Comment by pashminakazi** [comment]
@aharui Thank u so much
Issue resolved
