### ISSUE TITLE
Library Files Changes b/c of Porting to Royale should be reverted to become as same as Flex

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#635]
Project Details are :
https://paste.apache.org/cpo8y

These are library files in DBIZLIB

GridTextOrHTMLRenderer.as
Royale File : https://paste.apache.org/06vzx
Flex File : https://paste.apache.org/pbcnu
htmlText  and getStyle is causing error on console if uncomment it in Royale.

PickList_Simple.mxml
we were using skinClass="com.dbz.controls.ResizableTitleWindowSkin"
on creationComplete function initComponent we are using 

this.setStyle("skinClass", com.dbz.controls.ResizableTitleWindowSkin);
ResizableTitleWindowSkin is our custom Class
ResizableTitleWindowSkin : https://paste.apache.org/dpowg
How to use this file in Royale and what is replacement of SkinClass in Royale.

**Comment by aharui** [comment]
htmlText and getStyle have not been emulated on AdvancedDataGridItemRenderer.  You are welcome to do so.

I've been working on getting skinClass to work in order to fix #599.  Some skins may need modification.

Royale does not promise that all Flex code can be run without changes.  But the number of changes should be very small compared to a full port to any other JS framework.

**Comment by aharui** [comment]
skinClass is working for FormItem and hopefully for other SkinnableContainers, so try your custom skin and report problems.
