### ISSUE TITLE
ADG rows are not bold in Case of PickList

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#638]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to General Ledger from Select in Menu
Go to Misc-> Departments from Setups in Menu
File : com/dbz/modules/Common/dbzDepartmentSetup.mxml

dbzDepartmentSetup has 4 PickLists 
1st PickList is GL A/C Code when we open it,This picklist has title 'Chart of Account' 
Chart of Account is our another setup 

Go to General Ledger from Select in Menu
Go to Chart of Accounts -> Maintain from Setups in Menu
File : com/dbz/modules/GL/dbzChartOfAccountsSetup.mxml

dbzChartOfAccountsSetup ADG has Code and Title,Some of them are **bold**.
So when we open dbzChartOfAccountsSetup as a PickList in dbzDepartmentSetup why those rows are not Bold?
In Flex : 
![image](https://user-images.githubusercontent.com/42200979/71167698-fa5b6380-2276-11ea-8665-5ea8a1681382.png)

In Royale : 
![image](https://user-images.githubusercontent.com/42200979/71167726-07785280-2277-11ea-8a75-e7ddbc2094cc.png)

**Comment by aharui** [comment]
Did you verify that dbzDepartmentSetup was recently compiled?

**Comment by pashminakazi** [comment]
Yes dbzDepartmentSetup is recently compiled

**Comment by aharui** [comment]
When Chart of Accounts is displayed without bold, use the debugger's Elements view to find one of the renderers that should be bold.  Check its "royale_wrapper" property to verify that it is the custom renderer.  Then in Debugger sources check that AdvancedDataGridItemRenderer is the most recent one that has a setStyle method.

**Comment by pashminakazi** [comment]
I can't debug that deep in Royale because I never work on flex.

**Comment by aharui** [comment]
It is time for you to learn how.  This is a completely different debugging technique than debugging Flex because you are going to use the browser's debugger.  Use the Elements view in the debugger and expand the tree of elements until you find the renderers in the Chart of Accounts.  Then click on the renderer and view the Properties tab for the element.  There should be a "royale_wrapper" entry that should tell you the class name of the referenced object.  It should be your custom renderer.

**Comment by pashminakazi** [comment]
Ok thanks

**Comment by pashminakazi** [comment]
Issues resolved
