### ISSUE TITLE
Rate Setup ADG fields name issue

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#647]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Fixed Asset from Select in Menu
Go to Foreign Currency -> Rates from Setups in Menu
File : com/dbz/modules/Common/dbzFCRatesMain.mxml

dbzFCRatesMain is loading 3 modules

2nd module is Period-wise Exchange Rate
File : com/dbz/modules/Common/dbzExchangeRatePeriodwiseSetup.mxml

We you click on 2nd tab Period-wise Exchange Rate

In Royale
![image](https://user-images.githubusercontent.com/42200979/71665346-5a293280-2d7e-11ea-96a0-94d31c8beefd.png)

In Flex : 
![image](https://user-images.githubusercontent.com/42200979/71665412-a5dbdc00-2d7e-11ea-89a5-25d106a330f7.png)

**Comment by aharui** [comment]
I tried to debug this, but the console was so busy with AsyncTokens that it hung the debugger.  Is that expected?  If not, please fix that issue first so we can use the debugger.

Also, the column headers are different from Flex.  It looks like code that would set the column headers in com/dbz/modules/Common/dbzExchangeRatePeriodwiseSetup.mxml is commented out.

**Comment by pashminakazi** [comment]
I don't know why the console was so busy in dbzExchangeRatePeriodwiseSetup

**Comment by aharui** [comment]
The debugger is showing exceptions when dbzExchangeRatePeriodWiseSetup is trying to access its sibling module dbzForeignCurrencyRatesSetup.  There is code in dbzFCRatesMain that loads both as modules at the same time.  It is unsafe to rely on the order that the modules are initialized.

This problem needs to be resolved by rewriting the code that expects a particular load order before we do any further investigation of why the datagrid is not displaying anything as this exception appears to affect the fetching of the data provider.  (and result in the constant network calls because selectedItem remain null causing an endless series of server requests.
Direct sibling access is not good programming practice as it makes one thing dependent on the other.  It might be better to have a transaction with the parent to get the appropriate information.  So, instead of having dbzExchangeRatePeriodWiseSetup try to get the data on creationComplete, it can wait for an event or callback from the parent dbzFCRatesMain.  dbzFCRatesMain can watch for a creationComplete from dbzForeignCurrencyRatesSetup, get the information it needs and dispatch the event to tell dbzExchangeRatePeriodWiseSetup that the data it needs is ready.

**Comment by pashminakazi** [comment]
@aharui  Issue resolved Thanks
