### ISSUE TITLE
TypeError: Cannot read property 'length' of null (dbzUtil)

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#654]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Sales from Select in Menu
Go to Product -> Groups from Setups in Menu
File : com/dbz/modules/Common/dbzProductGroupSetup.mxml

Exception is in dbzUtil which is in Library
Code is missing in PickList because of this exception
![length property of dbzutil](https://user-images.githubusercontent.com/42200979/71812644-82c06d80-3099-11ea-8680-8a3c9fcb6a7e.gif)

**Comment by aharui** [comment]
PickList.mxml appears to have two ways of setting the dataProvider.  One is in the handleResult which looks correct, the other is in the mx:AdvancedDataGrid tag where it binds to arrDGDataProvider which appears to be incorrect as handleResult is expecting an ArrayCollection of ArrayCollections.

```
dataProvider="{arrDGDataProvider}"
```

This causes the labelFunction to throw the exception as it is getting an ArrayCollection instead of the list of items.

**Comment by pashminakazi** [comment]
@aharui  Issue resolved Thanks
