### ISSUE TITLE
DateField icon is hidden

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#665]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Sales from Select in Menu
Go to Carriage/Freight -> Customer Approved Depot from Setups in Menu
File : com/dbz/modules/Common/dbzApprovedDepotSetup.mxml

In Royale
![image](https://user-images.githubusercontent.com/42200979/71974929-9eac4680-3234-11ea-9a49-faecaeae5a94.png)

In Flex
![image](https://user-images.githubusercontent.com/42200979/71974942-a5d35480-3234-11ea-96f3-79611d64072f.png)

**Comment by aharui** [comment]
VDI is still not working.  One guess is that when you replace the TextInput, you need to set isAbsolute=false.  You can see an example in mx.controls.beads.DateFieldView.as

**Comment by pashminakazi** [comment]
I don't understand what are you saying

**Comment by aharui** [comment]
Did you see the usage of isAbsolute in DateFieldView?  Somewhere in MaskedDateField, a TextInput is created.  Right after creation, try adding isAbsolute=false.

**Comment by pashminakazi** [comment]
Please tell me
after which line 
MaskedDateField.as : https://paste.apache.org/r578f

**Comment by aharui** [comment]
After line 151

**Comment by pashminakazi** [comment]
after line 151 : textInput = new MaskedTextInput();
i have to add
COMPILE::JS
            {
                (textInput as MaskedTextInput).isAbsolute = false;
            }
right?

**Comment by aharui** [comment]
Yes, try that and see if that helps.

**Comment by pashminakazi** [comment]
Ok thanks

**Comment by pashminakazi** [comment]
Thanks its working now,but date icon should be like 
![image](https://user-images.githubusercontent.com/42200979/72592372-3c360300-3924-11ea-8b86-3870e7435f06.png)

**Comment by aharui** [comment]
I believe that Royale currently defaults to a down arrow character because it is available in more fonts and is more efficient than loading an image.  If it is important to your app to use some other visual, you will have to customize the DateField.  

I believe you are already using a DateField subclass throughout your application.  Just like you replace the TextInput, you can replace the Button.

**Comment by pashminakazi** [comment]
how can i replace icon of datefield?
![DateField](https://user-images.githubusercontent.com/42200979/72698975-4d6f5180-3b68-11ea-8f09-b91ec78616de.png)
this is the icon of dateField which i want,how to replace drop arrow with this image?
Please guide

**Comment by aharui** [comment]
I think you want to create a custom DateFieldView.  You should be able to combine both `org.apache.royale.html.beads.DateFieldView` and `mx.controls.beads.DateFieldView` and then modify how it creates the button to use ImageButton instead of TextButton.

You will probably have to set the width and height of the button because the browser may not load the icon in time for the measurement.

**Comment by pashminakazi** [comment]
@aharui I am unable to do this Please check the icon of Datefield

**Comment by aharui** [comment]
Is there a reason you must use a .png file?  Depending on the font you use, you may be able to use a special Unicode character like this one: 📅

It will be much easier to create a custom DateFieldView and replace the button.text than to use a .png file.
