### ISSUE TITLE
Tree menu expand vs click event should be separately handled 

### ISSUE THREAD

**Issue by nihavend** [apache/royale-asjs#670]
When using tree component in general (like windows explorer and Flex Tree), there is difference between action of expending tree and the node selection.
For the current royale implementation it is not. No differentiation between these two events.

I can only click the item and it is selected.

Currently the click on item expands the tree but the click event handler is not called.

**Comment by yishayw** [comment]
Can you add a test case so we can debug?

**Comment by nihavend** [comment]
@yishayw you can use the case in #673 if does not work i may prepare new one later today.

**Comment by yishayw** [comment]
This is a bit complicated because the default tree item renderer shows the collapse/expand icons as part of the text. We need to change the renderer so it is composed of two separate objects. The renderer controller could then listen to the expand/collapse component and create an itemExpandedOrCollapsed event which would then be handled by the tree controller.

**Comment by nihavend** [comment]
@yishayw would you suggest me to work on the issue looks like need some deep experience ?

**Comment by yishayw** [comment]
I think you can work on it. Look in defaults.css under MXRoyale to find out which item renderer and controllers I'm referring to. Let us know if you run into trouble. Thanks.
