### ISSUE TITLE
TitleWindow Hanged on setup can't click any where

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#692]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Inventory from Select in Menu
Go to PSSM -> Formation Setup from Setups in Menu
File : com/dbz/modules/Common/dbzFormationMaster.mxml
In FormationMaster  Setup dbzFormationDetail is used and when i open formation detail from formation master and came back to formation master everything is hanged in my application i can't click any where.
dbzFormationDetail is behaving same with mx:TitleWindow and s:TitleWindow.I also remove mx:bead from dbzFormationDetail.

![Titlewindow hanged](https://user-images.githubusercontent.com/42200979/72891314-cd96e200-3d35-11ea-9b2b-1b53181a9a22.gif)

**Comment by aharui** [comment]
Check the elements tab in the debugger to see if there are any elements that are blocking the application.

Then try pausing in the debugger and see what is code was paused.  You can continue and pause a few times to see if the same areas of code are in a loop.  If you are unsure, post some of the stack traces when you pause.

**Comment by aharui** [comment]
I did not see a PSSM entry in the Setup menu after switching to Inventory

**Comment by pashminakazi** [comment]
Wait i will check on VDI

**Comment by pashminakazi** [comment]
I Opened inventory Module Check at the last PSSM is there

**Comment by aharui** [comment]
It would save me much time if you stopped posting these videos and instead explained in words what is happening.  A screenshot or two may be helpful as well.

I am not able to quickly determine which popups are being displayed.  The TitleWindow appears to be hung because one of the popups is not having its modal overlay removed.  I checked the elements tab as I suggested 11 hours ago.  You could have done the same, and prepared the list of popups.  Instead, it is well past the end of my workday and so I must stop work for today and will have to continue tomorrow.
