### ISSUE TITLE
online TDJ DataGrid columns width issue

### ISSUE THREAD

**Issue by cristallium** [apache/royale-asjs#787]
Hi again Carlos, ;)

Playing with online tdj (`https://royale.apache.org/tourdejewel/#!datagrid_panel`), when I clic on a cell on first column (icon) of the 3th exemple (the orange header) then colums width have an issue (see capture)
I don't try to recompil TDJ with last SDK to see if the issue is solved or not

![image](https://user-images.githubusercontent.com/6851433/77428458-68647900-6dd8-11ea-9934-a1a60e315404.png)

By the way, could you confirm that `labelFunction `doesn't exist and I need to make an itemRenderer to customise output text ? Thanks !

**Comment by carlosrovira** [comment]
That's fixed in the actual state of the repo (develop). I still didn't update live example since many changes was done, and I still use to compare. For example in list there's an issue with selectedIndex not updating right in all cases when remove or add to dataprovider. In this case, better check the version you build locally.
Thanks!

**Comment by cristallium** [comment]
Thanks for your reactivity :)
For the labelFunction, I use an itemRenderer that worked fine.

**Comment by carlosrovira** [comment]
forgot about `labelFunction`. Therer's no support for now, but will think on something. We need to see what's the best approach for that. Thanks :)
