### ISSUE TITLE
Bad Label with Box Layout On RadioButtons

### ISSUE THREAD

**Issue by yishayw** [apache/royale-asjs#790]
Test case:
```
<?xml version="1.0" encoding="utf-8"?>
<mx:Application xmlns:fx="http://ns.adobe.com/mxml/2009"
                   xmlns:mx="library://ns.apache.org/royale/mx"
                   width="600" height="400" >
		<mx:HBox>
			<mx:RadioButton label="1" value="Radio 1"/>
			<mx:RadioButton label="2" value="Radio 2"/>
		</mx:HBox>
</mx:Application>
```

Note how "2" label is under the radio button icon

I think the width of the HBox is set to be 60px before the width of the last RadioButton is measured. Because of that the the last radio button's label overflows.

**Comment by yishayw** [comment]
With the example I posted, now both buttons have labels misaligned, and also selecting one doesn't deselect the other.

**Comment by yishayw** [comment]
>  also selecting one doesn't deselect the other.

I think I made a mistake here. The problem is I'm getting a selection that shouldn't happen, as can be seen here.

```
<mx:Application xmlns:fx="http://ns.adobe.com/mxml/2009" xmlns:mx="library://ns.apache.org/royale/mx" 
	applicationComplete="init()"
	width="600" height="400">
	<fx:Script>	
	<![CDATA[
		import mx.controls.RadioButton;

		private function init():void
		{
			var rb1:RadioButton = new RadioButton();
			rb1.value = "Radio 1";
			rb1.group = myGroup;
			var rb2:RadioButton = new RadioButton();
			rb2.value = "Radio 2";
			rb2.group = myGroup;
			myBox.addElement(rb1);
			myBox.addElement(rb2);
			rb1.label = "1";
			rb2.label = "2";
			myGroup.selectedValue = "Radio 2";
		}

	]]>
	</fx:Script>
	<mx:RadioButtonGroup id="myGroup" selectedValue=""/>
	<mx:HBox id="myBox">
	</mx:HBox>
</mx:Application>
```

**Comment by yishayw** [comment]
This was not a problem in Flex, probably because adding an element didn't immediately mean a check for selection according to group was made. 4aaaaca should provide a fix.

**Comment by yishayw** [comment]
The layout problem in this example is partly because the label isn't yet populated when the rb is measured.

**Comment by yishayw** [comment]
> The layout problem in this example is partly because the label isn't yet populated when the rb is measured.

Workaround (tested) for that is to call parent.dispatchEvent(new Event("layoutNeeded")) after a label change, but that seems wasteful.

**Comment by aharui** [comment]
Well, you can check if "isWidthSizedToContent()" before sending layoutNeeded, but otherwise, that is the way things work in MXRoyale.  In Flex, the RadioButton would call invalidateSize() on itself when the label changed, and the LayoutManager would eventually get around to calling invalidateSize() on the parent for you.  MXRoyale is currently not using a LayoutManager because of potential issues with deferred updates in browsers.  So yes, in many cases you have to tell the parent to layout again.

In Basic, the "rules" are different.  For PAYG reasons, Basic components should not automatically call layoutNeeded on the parent.  As you said, it would be wasteful in many scenarios.  Instead the app developer is supposed to hook up just the properties they know affect layout to the parent layout via binding, custom code, or LayoutChangeNotifier.
