### ISSUE TITLE
Flash Builder dosen't find royale-asjs as an SDK

### ISSUE THREAD

**Issue by yozef** [apache/royale-asjs#834]
I'm following the steps here: https://github.com/apache/royale-asjs/wiki/Flash-Builder-4.7

I've npm-ed to get `royale-asjs` and seemed to have downloaded successfully.

I moved it here: `Adobe Flash Builder 4.7/sdks/royale-asjs`.

When I try to add the SDK into Flash Builder, I get `Directory does not contain a Flex SDK`: 
<img width="400" alt="FB_ApacheRoyale" src="https://user-images.githubusercontent.com/287256/82082202-97e78180-96b5-11ea-963b-7153e1c42c71.png">

**Comment by piotrzarzycki21** [comment]
Thanks for reporting @yozef ! I really recommend you to look into one of the supported IDEs: [Moonshine IDE[(https://moonshine-ide.com/) or [VSCode](https://as3mxml.com/).

**Comment by carlosrovira** [comment]
Hi @yozef, while my comment will not solve your problem, and probably others with more use/knowledge of FB IDE can help you I want to let you know 2 things:

1.- Adobe FB IDE is deprecated for many years now and totally obsolete.
2.- Apache Royale recommends to use currently supported and active IDEs: Visual Studio Code with AS3&MXML extension and Moonshine.

I recommend you to try one of the IDEs above and try there the SDK. Sorry to not be able to say more in my case about FB, but many years since I worked with it :).

HTH

Carlos

**Comment by yozef** [comment]
I'm trying VSCode... the list of installed SDKs (which I think got fetched from Flash Builder):
<img width="250" alt="Screen Shot 2020-05-15 at 2 19 36 PM" src="https://user-images.githubusercontent.com/287256/82083109-290b2800-96b7-11ea-991f-27807481112b.png">

Not sure why it's not being recognized as an SDK

**Comment by yozef** [comment]
Update: 
I ended up downloading it from here: https://royale.apache.org/download/

Now I see it!

**Comment by carlosrovira** [comment]
Hi @yozef, great you get it! :)
can you please let us know from where was the previous SDK that gives you problem?
thanks!

**Comment by yozef** [comment]
There is a difference between the npm & direct download, and I downloaded the source code, the other is the compiled SDK... and that I think was the issue:
<img width="300" alt="Screen Shot 2020-05-15 at 2 35 01 PM" src="https://user-images.githubusercontent.com/287256/82084478-58bb2f80-96b9-11ea-8d4a-18bd3c8334ff.png">
