### ISSUE TITLE
Attachment file is uploading infinite times

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#853]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Inventory from Select in Menu
Go to Carriage/Freight from Setups in Menu
File : com/dbz/modules/Common/dbzDriverMasterSetup.mxml

Click on New Button and then attachment icon and then attach a file
**If you tick Pause on Exception** then system will upload file one time but **if you didn't tick on Pause on Exception** system will upload attachment infinite times

![image](https://user-images.githubusercontent.com/42200979/84250362-641d4180-ab25-11ea-8762-726789f0a340.png)
![image](https://user-images.githubusercontent.com/42200979/84250888-0b9a7400-ab26-11ea-9a79-4bedc4927720.png)

**Comment by aharui** [comment]
Is it uploading a file infinite times or is it adding the same item to the list over and over again?  Are there any exceptions if you pause on exceptions?

**Comment by pashminakazi** [comment]
Its adding same item over and over again,and if i tick on pause on
exception i will give exception uncaught TypeError: Cannot read property
'at_Name' of undefined

**Comment by aharui** [comment]
What is the call stack of the exception?

**Comment by pashminakazi** [comment]
I have logged into application and opened Driver Setup,Please check

**Comment by pashminakazi** [comment]
I logged out of VDI,Please login VDI,application is running and Driver Setup is opened

**Comment by aharui** [comment]
When you select a file to upload, the fn_FileSelect_EH is called in dbzAttachmentPopUp.
It calls strFileRef.load() after setting up a COMPLETE event handler that should call fn_FileUpload_EH.  But fn_FileUpload_EH also calls strFileRef.load() which should generate another load and COMPLETE event which seems like an infinite loop to me.

I think when you stop at the exception, the COMPLETE event is delayed.  It doesn't make sense to upload in the upload-is-complete handler.  It might have worked in Flex because the upload may not start immediately, but I think it might have different timing in Royale.  I recommend removing strFileRef.load in fn_FileUpload_EH.  I don't understand why it is there.

**Comment by pashminakazi** [comment]
@aharui Thank u so much issue resolved by removing strFileRef.load in fn_FileUpload_EH.
