### ISSUE TITLE
Saved Rows using itemEditor in Detail grid disappears

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#864]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Accounts Recieveable from Select in Menu
Go to Sales Commission Scheme Setup from Setups in Menu
File : com/dbz/modules/AR/dbzSalesCommissionScheme.mxml

Click on New Button then Plus (+) button and save one row and click ok,then if you click on Plus(+) button or Edit button the detail popup is showing Empty rows
I entered data in a row
![image](https://user-images.githubusercontent.com/42200979/84496439-65d23b00-acc6-11ea-80d6-1e87e834ac24.png)

now I clicked on OK button,one row is shown in detail grid 
![image](https://user-images.githubusercontent.com/42200979/84496492-784c7480-acc6-11ea-88e6-e062befb9068.png)

and again press + or edit button,Popup is Empty
![image](https://user-images.githubusercontent.com/42200979/84496550-8f8b6200-acc6-11ea-9201-0021dcb691a0.png)

then if i click on Plus(+) Button in PopupWindow to add new rows then old saved row will be shown
![image](https://user-images.githubusercontent.com/42200979/84496638-b6e22f00-acc6-11ea-933a-dba266797f3d.png)

**Comment by aharui** [comment]
It looks like the DetailGrid cannot layout properly because it is being set up before being added to the DOM so it cannot measure and layout correctly.

If you look at your dbzSalesCommissionScheme.fn_EditProduct, the arrDtlTransDP is added to (via addItem) before addPopUp.  You can try calling addPopUp before arrDtlTransDP is changed, or maybe call arrDtlTransDP.refresh() after addPopUp.

**Comment by pashminakazi** [comment]
@aharui Thank u so much Issue has been resolved by calling arrDtlTransDP.refresh() after addPopUp.
