### ISSUE TITLE
Jewel Application - percentWidth & percentHeight issue

### ISSUE THREAD

**Issue by javeiga-iest** [apache/royale-asjs#901]
Hi all,

I have been working with the Jewel Application control.

I have noticed something curious, and it is that when the child (in my case a ResponseView control) has the percentWidth or percentHeight property assigned, we assign to the application control a fixed width and height corresponding to the size of the child ...

This is the code snippet I'm talking about
https://github.com/apache/royale-asjs/blob/develop/frameworks/projects/Jewel/src/main/royale/org/apache/royale/jewel/Application.as

![image](https://user-images.githubusercontent.com/55754204/91303245-04d7e080-e7a8-11ea-953c-a1ad26ba0000.png)

Here is an example of the code transpiled to HTML;
![image](https://user-images.githubusercontent.com/55754204/91303781-cbec3b80-e7a8-11ea-8eb7-2362facd15ea.png)

The problem is that that size, we are passing through style in a fixed way, and it is never updated.
I don't know if this is being done for any particular reason... i think it could be removed.

thx in advance!

**Comment by carlosrovira** [comment]
Hi,

as stated in the docs [1], `ResponsiveView` should not add `width` and `height` since is for responsive applications and the view itself define itself to have 100% on both properties.

In exchange, `View` (see [2]) is a normal view that can define width and height (and use `BrowserResizeApplicationListener` bead to manage resizing if needed) while ResponsiveView does all of this without the need to define a listener for window's resize event since its reason is to respond to browser window resizing.

TDJ uses ResponsiveView that way:

```actionscript
<j:initialView>
	<local:MainContent/>
</j:initialView>
```
where `MainContent` is a `ResponsiveView` that doesn't specify width or height at all.

HTH.
Carlos

[1] https://apache.github.io/royale-docs/component-sets/jewel/responsiveview
[2] https://apache.github.io/royale-docs/component-sets/jewel/view

**Comment by javeiga-iest** [comment]
However, in the ResponsiveView construct, the percentage of width and height is set to 100 by default
https://github.com/apache/royale-asjs/blob/3fb70737d6f8a7f3b06e8b372babef30e59ab2ff/frameworks/projects/Jewel/src/main/royale/org/apache/royale/jewel/ResponsiveView.as
![image](https://user-images.githubusercontent.com/55754204/91312501-99484000-e7b4-11ea-8a1b-ed5706832394.png)

**Comment by javeiga-iest** [comment]
I just compiled the TDJ, and the problem reproduces:

_When you start the application, a fixed size is added to the style._
![image](https://user-images.githubusercontent.com/55754204/91408597-65b4f680-e844-11ea-82d6-dd9d678e7122.png)

_If we resize the application, the size does not change._
![image](https://user-images.githubusercontent.com/55754204/91408845-d3612280-e844-11ea-9864-3200d89d0dba.png)

**Comment by carlosrovira** [comment]
Ops, thanks for showing that. That line was for testing some issues and I thought I delete it before pushing the last refactor, but seems it was left by mistake. Sorry for the trouble, going to fix now. Thanks!
