### ISSUE TITLE
[Jewel][DateField] Add ability to disable range of dates 

### ISSUE THREAD

**Issue by piotrzarzycki21** [apache/royale-asjs#932]
DateField should have available bead which allows user specify min and max range date. Screenshot example from Vuetify where you cannot click on dates above 13 Nov:

![vuetify_example](https://user-images.githubusercontent.com/24554795/99047824-0e960680-2595-11eb-82f8-e8fdfce71755.png)

**Comment by carlosrovira** [comment]
Hi Piotr, thanks for adding this.
I can support you on this in the styles/theme side to make it look as close to jewel theme as possible

**Comment by piotrzarzycki21** [comment]
Thanks! Maybe it will work nicely just out of the box. You can shed some light how is build in HTML cell which holds day in DateChooser. What will happen if I make it disable - does it go gray in a similar way how Button goes when you add Disable bead ?

**Comment by carlosrovira** [comment]
DateChooser use Table (DateChooserTable) to build the dates. So echa Date is a TableCell. The disabled style is setup at "table level". Right now there's no isolated table cell disabled style. That will need to be done. You can set up a temporal basic style in the Jewel library and as you finish the implementation I can go over there and create the appropiate styling and move the required to Jewel Themes.

**Comment by piotrzarzycki21** [comment]
@carlosrovira Here is example which contains bead and current state of my implementation. It has Maven pom file, so you should be able to build it. I didn't test it too much - it does block some dates, so something has started to work. 

I will have time to back to that at the end of January probably - if you beat me earlier it would be great.

[DateChooserExample.zip](https://github.com/apache/royale-asjs/files/5750056/DateChooserExample.zip)

**Comment by piotrzarzycki21** [comment]
@carlosrovira I did look again into that and over the road I see that there is an issue with DateChooser. I was using newest nightly to build TourDeJewel. 

![datechooser_issue](https://user-images.githubusercontent.com/24554795/103347699-01c36880-4a98-11eb-89ac-fa2283c3f6ed.gif)

**Comment by carlosrovira** [comment]
Hi Piotr,
Thanks for let me know. Just fixed it. It was caused by a recent update done in ListView where we want to perform the scrollToIndex in all kind of actions but not when we click on items. I extract that so in TableView we don't want to have that functionality.

**Comment by carlosrovira** [comment]
Hi Piotr,

I added the bead with some updates to Jewel and added as well styles to JewelTheme to allow display the disabled cells.
I think the bead is very close to finish. I see to points to fix:
- Fix the enabled/disable for cells since right now is not taking the right ones.
- Run the enable/disable code when click on datechooser navigation buttons
I'll continue checking and working on it soon

**Comment by carlosrovira** [comment]
Hi Piotr, just complete the bead and seems to work ok. Also added an example in TDJ's DateComponentsPlayGround page.

**Comment by piotrzarzycki21** [comment]
Thank you @carlosrovira for help with that :)

**Comment by piotrzarzycki21** [comment]
@carlosrovira One of the reason why I have started working on that bead was that I wanted to use it in DateField, instead of DateChooser. DateField using DateChooser - in order to apply that bead to DateField I will extend DateFieldView, but do you think it should be easiest way of adding that beat to DateField ?

**Comment by carlosrovira** [comment]
Hi @piotrzarzycki21, I think we should be able to do that kind of things without the need to extend DateFieldView. In this case, we can throw an event in that view that signals the popup is created and ready and then create another bead that simply operate listening to that event and adding the new DateChooser bead. So that way for the user the only need will be to add the new bead to the DateField.

**Comment by piotrzarzycki21** [comment]
@carlosrovira it is still seems to be complicated plus how user provides it’s minDate and maxDate? Event can be helpful. I think user should have an ability to add our Date range bead in mxml and view of date field should handle that.

**Comment by carlosrovira** [comment]
User should use the new bead in the same way he does in DateChooser providing `minDate` and `maxDate`. The new event should be used to hook these values in the popup that we create each time

**Comment by carlosrovira** [comment]
Hi @piotrzarzycki21 just created the bead. The system used is the same we use in Jewel ComboBox with the same events, take a look. I also added the corresponding example to TDJ.

**Comment by carlosrovira** [comment]
Hi Piotr, I did more updates to this one:

- Now the bead support to set just one of the restriction (min or max date) or both as before
- I added code to remove selectionDate if selection was out of the range, but then commented out and left for an extension since I think maybe not all people would want to do this and seems something optional, so better left for other bead. (Note: if the remove selection code is needed to craft another bead I left the lines commented to use it there easily).
- Instead, I updated styles so "selected disabled dates" are now colorized correctly.

I think I'm done for now with this extension.
